<?php
/**
 * @file
 * tax_meas_electrical.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_meas_electrical_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => '100 kHz',
    'description' => NULL,
    'format' => NULL,
    'weight' => 4,
    'uuid' => '03faa852-504d-4fc0-b833-51b63d86d353',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1937,
          'revision_id' => 1937,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498388,
          'changed' => 1460498388,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '558e461a-4c43-4cdd-9c9b-e5ed3f542c28',
    ),
  );
  $terms[] = array(
    'name' => '1 mHz',
    'description' => NULL,
    'format' => NULL,
    'weight' => 1,
    'uuid' => '1cd25815-44bb-4f6a-b1db-d62a8f9e20e1',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1934,
          'revision_id' => 1934,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498388,
          'changed' => 1460498388,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '558e461a-4c43-4cdd-9c9b-e5ed3f542c28',
    ),
  );
  $terms[] = array(
    'name' => '50 kHz',
    'description' => NULL,
    'format' => NULL,
    'weight' => 3,
    'uuid' => '3e68a8d6-bfc5-48ad-b74d-ed65ff5c06f8',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1936,
          'revision_id' => 1936,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498388,
          'changed' => 1460498388,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '558e461a-4c43-4cdd-9c9b-e5ed3f542c28',
    ),
  );
  $terms[] = array(
    'name' => 'Frequency',
    'description' => NULL,
    'format' => NULL,
    'weight' => 14,
    'uuid' => '558e461a-4c43-4cdd-9c9b-e5ed3f542c28',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1772,
          'revision_id' => 1772,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413116,
          'changed' => 1460413116,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 0,
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5a0898aa-32e0-493c-99ca-1c43261dcdf2',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1930,
          'revision_id' => 1930,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498388,
          'changed' => 1460498388,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a7b1c587-3a48-4fac-b7b1-65c381518331',
    ),
  );
  $terms[] = array(
    'name' => 0,
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '69ebcef8-f467-42f6-80df-f49181666b8b',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1933,
          'revision_id' => 1933,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498388,
          'changed' => 1460498388,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '558e461a-4c43-4cdd-9c9b-e5ed3f542c28',
    ),
  );
  $terms[] = array(
    'name' => '100,000 microF',
    'description' => NULL,
    'format' => NULL,
    'weight' => 2,
    'uuid' => '78e4c711-6d1d-4ae8-a623-23bb39c850f1',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1932,
          'revision_id' => 1932,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498388,
          'changed' => 1460498388,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a7b1c587-3a48-4fac-b7b1-65c381518331',
    ),
  );
  $terms[] = array(
    'name' => '20 kHz',
    'description' => NULL,
    'format' => NULL,
    'weight' => 2,
    'uuid' => '7c58ce67-9a66-4259-8396-09bb2edb59ff',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1935,
          'revision_id' => 1935,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498388,
          'changed' => 1460498388,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '558e461a-4c43-4cdd-9c9b-e5ed3f542c28',
    ),
  );
  $terms[] = array(
    'name' => '200 kHz',
    'description' => NULL,
    'format' => NULL,
    'weight' => 5,
    'uuid' => '82a00c55-7be9-4d9c-8eb0-f8280078e28d',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1938,
          'revision_id' => 1938,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498388,
          'changed' => 1460498388,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '558e461a-4c43-4cdd-9c9b-e5ed3f542c28',
    ),
  );
  $terms[] = array(
    'name' => 'Continuity',
    'description' => NULL,
    'format' => NULL,
    'weight' => 11,
    'uuid' => '87df68be-64db-4c10-b02f-a8d951fb69c0',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1771,
          'revision_id' => 1771,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413116,
          'changed' => 1460413116,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Capacitance',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a7b1c587-3a48-4fac-b7b1-65c381518331',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1769,
          'revision_id' => 1769,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413116,
          'changed' => 1460413116,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Duty cycle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 13,
    'uuid' => 'a876b305-4b6b-4268-b50b-1190bb55f6be',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1774,
          'revision_id' => 1774,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413116,
          'changed' => 1460413116,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Frequency sourcing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 15,
    'uuid' => 'addc1886-35ae-4b49-9a7c-f3d3b0d02aa8',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1773,
          'revision_id' => 1773,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413116,
          'changed' => 1460413116,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '10,000 micoF',
    'description' => NULL,
    'format' => NULL,
    'weight' => 1,
    'uuid' => 'd0bddfa6-8a34-4b78-962e-5e3bad28f649',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1931,
          'revision_id' => 1931,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498388,
          'changed' => 1460498388,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a7b1c587-3a48-4fac-b7b1-65c381518331',
    ),
  );
  $terms[] = array(
    'name' => 'Diode test',
    'description' => NULL,
    'format' => NULL,
    'weight' => 12,
    'uuid' => 'e0f3908d-0d97-4c7b-9296-3c2cff30eeaf',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1776,
          'revision_id' => 1776,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413116,
          'changed' => 1460413116,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Conductance',
    'description' => NULL,
    'format' => NULL,
    'weight' => 10,
    'uuid' => 'e7ddc5ea-fb8a-4330-a0e8-54ac5df2a1c1',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1770,
          'revision_id' => 1770,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413116,
          'changed' => 1460413116,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Pulse width',
    'description' => NULL,
    'format' => NULL,
    'weight' => 16,
    'uuid' => 'eaae0170-209c-4c59-b08b-d0da9cbb0028',
    'vocabulary_machine_name' => 'electrical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1775,
          'revision_id' => 1775,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413116,
          'changed' => 1460413116,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  return $terms;
}
