<?php
/**
 * @file
 * tax_main_menu.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_main_menu_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Supplier Handbook',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 4,
    'uuid' => '03d631c9-98a5-4ad5-8f97-30fd67d05c8e',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Supplier Handbook',
          'format' => NULL,
          'safe_value' => 'Supplier Handbook',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'supplier-handbook',
          'format' => NULL,
          'safe_value' => 'supplier-handbook',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1958,
          'revision_id' => 1958,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670353,
          'changed' => 1460670353,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Software Downloads',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 14,
    'uuid' => '078839ee-af0d-45e2-b027-10f98aec3f84',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Software Downloads',
          'format' => NULL,
          'safe_value' => 'Software Downloads',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'software-downloads',
          'format' => NULL,
          'safe_value' => 'software-downloads',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2043,
          'revision_id' => 2043,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673305,
          'changed' => 1460673305,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'IR Windows',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => '0b7c2c9b-7da3-4e96-8a85-6597b7a8dc23',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'IR Windows',
          'format' => NULL,
          'safe_value' => 'IR Windows',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'ir-windows',
          'format' => NULL,
          'safe_value' => 'ir-windows',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1993,
          'revision_id' => 1993,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671708,
          'changed' => 1460671708,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e70dab3b-950d-459d-9cae-bc734e5491ff',
    ),
  );
  $terms[] = array(
    'name' => 'Contact Us',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => '0d032e00-fcd7-456c-9748-a6d78eff194d',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Contact Us',
          'format' => NULL,
          'safe_value' => 'Contact Us',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'contact-us',
          'format' => NULL,
          'safe_value' => 'contact-us',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2026,
          'revision_id' => 2026,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672705,
          'changed' => 1460672705,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e026ebfe-ee3d-468b-ba6b-55eb00fb6079',
    ),
  );
  $terms[] = array(
    'name' => 'Temperature Calibrators',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '0fe84e01-c969-4dfc-bac6-d66aa298b5bc',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Temperature Calibrators',
          'format' => NULL,
          'safe_value' => 'Temperature Calibrators',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'temperature-calibrators',
          'format' => NULL,
          'safe_value' => 'temperature-calibrators',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1969,
          'revision_id' => 1969,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670394,
          'changed' => 1460670394,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'dffdbc8c-f9a4-47da-8e31-533d1a8d2c50',
    ),
  );
  $terms[] = array(
    'name' => 'Insulation Testers',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 5,
    'uuid' => '10ad3de0-4587-44a8-8ffc-1952382f843b',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Insulation Testers',
          'format' => NULL,
          'safe_value' => 'Insulation Testers',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'insulation-testers',
          'format' => NULL,
          'safe_value' => 'insulation-testers',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1976,
          'revision_id' => 1976,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671082,
          'changed' => 1460671082,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'ef76bf6c-3af7-48b0-870d-4dc1a38bd673',
    ),
  );
  $terms[] = array(
    'name' => 'Laser Alignment',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '12367162-df65-4cbc-b797-6f52528cfc51',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Laser Alignment',
          'format' => NULL,
          'safe_value' => 'Laser Alignment',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'laser-alignment',
          'format' => NULL,
          'safe_value' => 'laser-alignment',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1989,
          'revision_id' => 1989,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671691,
          'changed' => 1460671691,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '5c13d9d0-5aac-4730-ae64-365830156e8c',
    ),
  );
  $terms[] = array(
    'name' => 'Digital Multimeters',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '15bc8996-5d76-4990-bed5-6aca8b17002a',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Digital Multimeters',
          'format' => NULL,
          'safe_value' => 'Digital Multimeters',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'digital-multimeters',
          'format' => NULL,
          'safe_value' => 'digital-multimeters',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1973,
          'revision_id' => 1973,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671069,
          'changed' => 1460671069,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'ef76bf6c-3af7-48b0-870d-4dc1a38bd673',
    ),
  );
  $terms[] = array(
    'name' => 'Safety Notices',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 12,
    'uuid' => '161bd585-82ad-4827-809d-5443a5726fb6',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Safety Notices',
          'format' => NULL,
          'safe_value' => 'Safety Notices',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'safety-notices',
          'format' => NULL,
          'safe_value' => 'safety-notices',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2041,
          'revision_id' => 2041,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673295,
          'changed' => 1460673295,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Troubleshooting Motors & Drives',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 4,
    'uuid' => '1c14dd7f-8824-48e5-803a-8ff65bca4343',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Troubleshooting Motors & Drives',
          'format' => NULL,
          'safe_value' => 'Troubleshooting Motors &amp; Drives',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'troubleshooting-motors-drives',
          'format' => NULL,
          'safe_value' => 'troubleshooting-motors-drives',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2016,
          'revision_id' => 2016,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672661,
          'changed' => 1460672661,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '293575ab-f1b2-4c82-a2f3-0a6f5f84ddd4',
    ),
  );
  $terms[] = array(
    'name' => 'Energy Efficiency',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => '1c577e53-37fe-4218-9fd4-3e7adcd3d236',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Energy Efficiency',
          'format' => NULL,
          'safe_value' => 'Energy Efficiency',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'energy-efficiency',
          'format' => NULL,
          'safe_value' => 'energy-efficiency',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1999,
          'revision_id' => 1999,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671736,
          'changed' => 1460671736,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '232a6652-260d-4dce-8e76-d7ea8b59abf6',
    ),
  );
  $terms[] = array(
    'name' => 'Companies',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '1d411a78-b9f4-4f89-a3f1-62df9cedf3fb',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Companies',
          'format' => NULL,
          'safe_value' => 'Companies',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'companies',
          'format' => NULL,
          'safe_value' => 'companies',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2025,
          'revision_id' => 2025,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672700,
          'changed' => 1460672700,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e026ebfe-ee3d-468b-ba6b-55eb00fb6079',
    ),
  );
  $terms[] = array(
    'name' => 'Data Acquisition',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => '1d53cb84-40e5-4750-8f9b-6ae7cb0cf56a',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Data Acquisition',
          'format' => NULL,
          'safe_value' => 'Data Acquisition',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'data-acquisition',
          'format' => NULL,
          'safe_value' => 'data-acquisition',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1981,
          'revision_id' => 1981,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671105,
          'changed' => 1460671105,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'dc023e36-ece5-48aa-b2d6-297a81567619',
    ),
  );
  $terms[] = array(
    'name' => 'Test Tools Basics',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '1e9bcadd-9587-4652-814c-39523b726b53',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Test Tools Basics',
          'format' => NULL,
          'safe_value' => 'Test Tools Basics',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'test-tools-basics',
          'format' => NULL,
          'safe_value' => 'test-tools-basics',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2010,
          'revision_id' => 2010,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672635,
          'changed' => 1460672635,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    ),
  );
  $terms[] = array(
    'name' => 'Multifunction Calibrators',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '204062cf-f2a0-4c18-8837-3b427eb9ab91',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Multifunction Calibrators',
          'format' => NULL,
          'safe_value' => 'Multifunction Calibrators',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'multifunction-calibrators',
          'format' => NULL,
          'safe_value' => 'multifunction-calibrators',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1967,
          'revision_id' => 1967,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670403,
          'changed' => 1460670403,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'dffdbc8c-f9a4-47da-8e31-533d1a8d2c50',
    ),
  );
  $terms[] = array(
    'name' => 'Test & Measurement Basics',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '22dae31b-9b60-4eb3-81a9-78a6a12e7e38',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Test & Measurement Basics',
          'format' => NULL,
          'safe_value' => 'Test &amp; Measurement Basics',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'test-measurement-basics',
          'format' => NULL,
          'safe_value' => 'test-measurement-basics',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2008,
          'revision_id' => 2008,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672627,
          'changed' => 1460672627,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    ),
  );
  $terms[] = array(
    'name' => 'Solutions',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 99,
    'uuid' => '232a6652-260d-4dce-8e76-d7ea8b59abf6',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Solutions',
          'format' => NULL,
          'safe_value' => 'Solutions',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-connect-assets',
          'format' => NULL,
          'safe_value' => 'fluke-connect-assets',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1997,
          'revision_id' => 1997,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671727,
          'changed' => 1460671727,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'For Educators',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 8,
    'uuid' => '23c74789-cca3-4179-90d5-1b2eb9559fa3',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'For Educators',
          'format' => NULL,
          'safe_value' => 'For Educators',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'educators',
          'format' => NULL,
          'safe_value' => 'educators',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2021,
          'revision_id' => 2021,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672683,
          'changed' => 1460672683,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    ),
  );
  $terms[] = array(
    'name' => 'Radiation safety',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 17,
    'uuid' => '25cb2657-c7eb-4b91-86c4-5d5c026a3e60',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Radiation safety',
          'format' => NULL,
          'safe_value' => 'Radiation safety',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'radiation-safety',
          'format' => NULL,
          'safe_value' => 'radiation-safety',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2407,
          'revision_id' => 2407,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1461364882,
          'changed' => 1461364882,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Applications',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => '293575ab-f1b2-4c82-a2f3-0a6f5f84ddd4',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Applications',
          'format' => NULL,
          'safe_value' => 'Applications',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'applications',
          'format' => NULL,
          'safe_value' => 'applications',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2011,
          'revision_id' => 2011,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672640,
          'changed' => 1460672640,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    ),
  );
  $terms[] = array(
    'name' => 'Promotions & Contests',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => '2a18047b-4e66-4702-bfa6-72faeeda2fb5',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Promotions & Contests',
          'format' => NULL,
          'safe_value' => 'Promotions &amp; Contests',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'promotions-contests',
          'format' => NULL,
          'safe_value' => 'promotions-contests',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1957,
          'revision_id' => 1957,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670348,
          'changed' => 1460670348,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Manuals',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 7,
    'uuid' => '301e9f34-73c8-4177-a872-aad67916cd60',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Manuals',
          'format' => NULL,
          'safe_value' => 'Manuals',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'manuals',
          'format' => NULL,
          'safe_value' => 'manuals',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2036,
          'revision_id' => 2036,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673273,
          'changed' => 1460673273,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Manufacturing',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '31bf35c4-1ec2-4920-9ee5-67950b98b881',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Manufacturing',
          'format' => NULL,
          'safe_value' => 'Manufacturing',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'manufacturing',
          'format' => NULL,
          'safe_value' => 'manufacturing',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2002,
          'revision_id' => 2002,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671756,
          'changed' => 1460671756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '32c47502-3003-4b6d-a999-8da0478755be',
    ),
  );
  $terms[] = array(
    'name' => 'Industries',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '32c47502-3003-4b6d-a999-8da0478755be',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Industries',
          'format' => NULL,
          'safe_value' => 'Industries',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'industries',
          'format' => NULL,
          'safe_value' => 'industries',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2000,
          'revision_id' => 2000,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671740,
          'changed' => 1460671740,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '232a6652-260d-4dce-8e76-d7ea8b59abf6',
    ),
  );
  $terms[] = array(
    'name' => 'Where to Buy',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 102,
    'uuid' => '32d7b57f-8694-494d-856f-d26348fb6153',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Where to Buy',
          'format' => NULL,
          'safe_value' => 'Where to Buy',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'where-to-buy',
          'format' => NULL,
          'safe_value' => 'where-to-buy',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2046,
          'revision_id' => 2046,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673320,
          'changed' => 1460673320,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Visual IR Thermometers',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => '38c71d68-f2a5-4943-8b28-827666b17c7a',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Visual IR Thermometers',
          'format' => NULL,
          'safe_value' => 'Visual IR Thermometers',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'visual-ir-thermometers',
          'format' => NULL,
          'safe_value' => 'visual-ir-thermometers',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1995,
          'revision_id' => 1995,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671719,
          'changed' => 1460671719,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e70dab3b-950d-459d-9cae-bc734e5491ff',
    ),
  );
  $terms[] = array(
    'name' => 'Tradeshows & Seminars',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 5,
    'uuid' => '39fcca03-a6ec-42da-ba3a-fd4437543359',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Tradeshows & Seminars',
          'format' => NULL,
          'safe_value' => 'Tradeshows &amp; Seminars',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'tradeshows-seminars',
          'format' => NULL,
          'safe_value' => 'tradeshows-seminars',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2018,
          'revision_id' => 2018,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672670,
          'changed' => 1460672670,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    ),
  );
  $terms[] = array(
    'name' => 'Training Library',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 9,
    'uuid' => '3a177537-ea5d-4556-8aed-6f3931dae171',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Training Library',
          'format' => NULL,
          'safe_value' => 'Training Library',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'training-library',
          'format' => NULL,
          'safe_value' => 'training-library',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2022,
          'revision_id' => 2022,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672687,
          'changed' => 1460672687,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    ),
  );
  $terms[] = array(
    'name' => 'Why Professionals Choose Fluke',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 6,
    'uuid' => '3baa1d21-468b-4721-8e87-3ed4758c9dae',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Why Professionals Choose Fluke',
          'format' => NULL,
          'safe_value' => 'Why Professionals Choose Fluke',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'why-professionals-choose-fluke',
          'format' => NULL,
          'safe_value' => 'why-professionals-choose-fluke',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1960,
          'revision_id' => 1960,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670363,
          'changed' => 1460670363,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Power & Energy Loggers',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 6,
    'uuid' => '3cc4fa5a-96d5-40c9-a6aa-818fafddfc31',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Power & Energy Loggers',
          'format' => NULL,
          'safe_value' => 'Power &amp; Energy Loggers',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'power-energy-loggers',
          'format' => NULL,
          'safe_value' => 'power-energy-loggers',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1977,
          'revision_id' => 1977,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671087,
          'changed' => 1460671087,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'ef76bf6c-3af7-48b0-870d-4dc1a38bd673',
    ),
  );
  $terms[] = array(
    'name' => 'Earth Ground',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => '3dc0ad67-a40e-447a-b31f-99e884742aee',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Earth Ground',
          'format' => NULL,
          'safe_value' => 'Earth Ground',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'earth-ground',
          'format' => NULL,
          'safe_value' => 'earth-ground',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1974,
          'revision_id' => 1974,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671073,
          'changed' => 1460671073,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'ef76bf6c-3af7-48b0-870d-4dc1a38bd673',
    ),
  );
  $terms[] = array(
    'name' => 'Online Courses',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 7,
    'uuid' => '406e2835-b0cc-433c-9212-9f39a6b919c8',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Online Courses',
          'format' => NULL,
          'safe_value' => 'Online Courses',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'online-courses',
          'format' => NULL,
          'safe_value' => 'online-courses',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2020,
          'revision_id' => 2020,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672678,
          'changed' => 1460672678,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    ),
  );
  $terms[] = array(
    'name' => 'Oil & Gas',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '4367ed88-1123-4378-b7f8-43919ff2a8cb',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Oil & Gas',
          'format' => NULL,
          'safe_value' => 'Oil &amp; Gas',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'oil-and-gas',
          'format' => NULL,
          'safe_value' => 'oil-and-gas',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2004,
          'revision_id' => 2004,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671744,
          'changed' => 1460671744,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '32c47502-3003-4b6d-a999-8da0478755be',
    ),
  );
  $terms[] = array(
    'name' => 'Pressure Calibrators',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => '4c674a8c-ad3e-4fff-99f6-db7f563bc891',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Pressure Calibrators',
          'format' => NULL,
          'safe_value' => 'Pressure Calibrators',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'pressure-calibrators',
          'format' => NULL,
          'safe_value' => 'pressure-calibrators',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1968,
          'revision_id' => 1968,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670398,
          'changed' => 1460670398,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'dffdbc8c-f9a4-47da-8e31-533d1a8d2c50',
    ),
  );
  $terms[] = array(
    'name' => 'Pressure Calibration',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '4dc674f3-40e7-45ad-9ce3-3e940a051c5c',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Pressure Calibration',
          'format' => NULL,
          'safe_value' => 'Pressure Calibration',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'pressure-calibration',
          'format' => NULL,
          'safe_value' => 'pressure-calibration',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2014,
          'revision_id' => 2014,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672653,
          'changed' => 1460672653,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '293575ab-f1b2-4c82-a2f3-0a6f5f84ddd4',
    ),
  );
  $terms[] = array(
    'name' => 'Firmware Downloads',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 4,
    'uuid' => '4f2d34f1-6d06-4a5a-9cef-cd323cc94dbb',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Firmware Downloads',
          'format' => NULL,
          'safe_value' => 'Firmware Downloads',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'firmware-downloads',
          'format' => NULL,
          'safe_value' => 'firmware-downloads',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2033,
          'revision_id' => 2033,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673259,
          'changed' => 1460673259,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Fluke Tools',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '53cf4a2e-6222-4169-a188-a091ca977bd9',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluke Tools',
          'format' => NULL,
          'safe_value' => 'Fluke Tools',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-tools',
          'format' => NULL,
          'safe_value' => 'fluke-tools',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2047,
          'revision_id' => 2047,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673431,
          'changed' => 1460673431,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '32d7b57f-8694-494d-856f-d26348fb6153',
    ),
  );
  $terms[] = array(
    'name' => 'Directions',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 4,
    'uuid' => '56c3ce17-78d7-4aca-a2b7-e048b3b6c7c2',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Directions',
          'format' => NULL,
          'safe_value' => 'Directions',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'directions',
          'format' => NULL,
          'safe_value' => 'directions',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2029,
          'revision_id' => 2029,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673235,
          'changed' => 1460673235,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e026ebfe-ee3d-468b-ba6b-55eb00fb6079',
    ),
  );
  $terms[] = array(
    'name' => 'Thermometers',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '57280ea8-47c5-4d73-bf3e-82cd0c75085f',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Thermometers',
          'format' => NULL,
          'safe_value' => 'Thermometers',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'thermometers',
          'format' => NULL,
          'safe_value' => 'thermometers',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1994,
          'revision_id' => 1994,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671715,
          'changed' => 1460671715,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e70dab3b-950d-459d-9cae-bc734e5491ff',
    ),
  );
  $terms[] = array(
    'name' => 'Preventive Maintenance',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => '5c070c4e-428b-41bb-a051-68b6202dce29',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Preventive Maintenance',
          'format' => NULL,
          'safe_value' => 'Preventive Maintenance',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'preventive-maintenance',
          'format' => NULL,
          'safe_value' => 'preventive-maintenance',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2005,
          'revision_id' => 2005,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671761,
          'changed' => 1460671761,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '232a6652-260d-4dce-8e76-d7ea8b59abf6',
    ),
  );
  $terms[] = array(
    'name' => 'Mechancial Maintenance',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 15,
    'uuid' => '5c13d9d0-5aac-4730-ae64-365830156e8c',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Mechancial Maintenance',
          'format' => NULL,
          'safe_value' => 'Mechancial Maintenance',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'mechancial-maintenance',
          'format' => NULL,
          'safe_value' => 'mechancial-maintenance',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1988,
          'revision_id' => 1988,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671687,
          'changed' => 1460671687,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Mining & Metals',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => '5ea0c643-913a-4381-8d68-f7b1f89ef8dc',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Mining & Metals',
          'format' => NULL,
          'safe_value' => 'Mining &amp; Metals',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'mining-and-metals',
          'format' => NULL,
          'safe_value' => 'mining-and-metals',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2003,
          'revision_id' => 2003,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671748,
          'changed' => 1460671748,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '32c47502-3003-4b6d-a999-8da0478755be',
    ),
  );
  $terms[] = array(
    'name' => 'Fluke Connect',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 98,
    'uuid' => '5edc5b7a-bb76-4028-beee-40fa0f6b7e12',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluke Connect',
          'format' => NULL,
          'safe_value' => 'Fluke Connect',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-connect',
          'format' => NULL,
          'safe_value' => 'fluke-connect',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1996,
          'revision_id' => 1996,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671723,
          'changed' => 1460671723,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Home',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 61,
    'uuid' => '605b600f-c467-4c0a-be34-5d10fe61872d',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-in' => array(
        0 => array(
          'value' => 'Home',
          'format' => NULL,
          'safe_value' => 'Home',
        ),
      ),
      'en-us' => array(
        0 => array(
          'value' => 'Home',
          'format' => NULL,
          'safe_value' => 'Home',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-in' => array(
        0 => array(
          'value' => 'home',
          'format' => NULL,
          'safe_value' => 'home',
        ),
      ),
      'en-us' => array(
        0 => array(
          'value' => 'home',
          'format' => NULL,
          'safe_value' => 'home',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1952,
          'revision_id' => 1952,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460669583,
          'changed' => 1460669583,
          'blocking' => 0,
        ),
        'en-in' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1952,
          'revision_id' => 1952,
          'language' => 'en-in',
          'source' => 'en-us',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460669623,
          'changed' => 1460669623,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Fluke Software',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 11,
    'uuid' => '66ad3207-bdf2-4d67-bbae-4445f634da7b',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluke Software',
          'format' => NULL,
          'safe_value' => 'Fluke Software',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-software',
          'format' => NULL,
          'safe_value' => 'fluke-software',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1983,
          'revision_id' => 1983,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671114,
          'changed' => 1460671114,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Portable appliance testers',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 16,
    'uuid' => '6717caa6-be5a-411b-a97b-f38bfb760afa',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-gb' => array(
        0 => array(
          'value' => 'Portable appliance testers',
          'format' => NULL,
          'safe_value' => 'Portable appliance testers',
        ),
      ),
      'en-in' => array(
        0 => array(
          'value' => 'Portable appliance testers',
          'format' => NULL,
          'safe_value' => 'Portable appliance testers',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-gb' => array(
        0 => array(
          'value' => 'portable-appliance-testers',
          'format' => NULL,
          'safe_value' => 'portable-appliance-testers',
        ),
      ),
      'en-in' => array(
        0 => array(
          'value' => 'portable-appliance-testers',
          'format' => NULL,
          'safe_value' => 'portable-appliance-testers',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-gb',
      'data' => array(
        'en-gb' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2408,
          'revision_id' => 2408,
          'language' => 'en-gb',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1461365235,
          'changed' => 1461365235,
          'blocking' => 0,
        ),
        'en-in' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2408,
          'revision_id' => 2408,
          'language' => 'en-in',
          'source' => 'en-gb',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1461365521,
          'changed' => 1461365521,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Bench Instruments',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '68cd6587-3fae-44a7-84b5-2c42a72fb407',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Bench Instruments',
          'format' => NULL,
          'safe_value' => 'Bench Instruments',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'bench-instruments',
          'format' => NULL,
          'safe_value' => 'bench-instruments',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1980,
          'revision_id' => 1980,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671132,
          'changed' => 1460671132,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'dc023e36-ece5-48aa-b2d6-297a81567619',
    ),
  );
  $terms[] = array(
    'name' => 'Support',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 101,
    'uuid' => '691d7bb7-7eaa-418d-a877-c10d73605756',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Support',
          'format' => NULL,
          'safe_value' => 'Support',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'support',
          'format' => NULL,
          'safe_value' => 'support',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2023,
          'revision_id' => 2023,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672692,
          'changed' => 1460672692,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Instrument Security',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 6,
    'uuid' => '697a0204-104b-4c32-9455-79cafb5636f1',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Instrument Security',
          'format' => NULL,
          'safe_value' => 'Instrument Security',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'instrument-security',
          'format' => NULL,
          'safe_value' => 'instrument-security',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2035,
          'revision_id' => 2035,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673268,
          'changed' => 1460673268,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Careers',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '6c88f157-8841-4155-8b84-3d231a4ed90d',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Careers',
          'format' => NULL,
          'safe_value' => 'Careers',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'careers',
          'format' => NULL,
          'safe_value' => 'careers',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2027,
          'revision_id' => 2027,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673240,
          'changed' => 1460673240,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e026ebfe-ee3d-468b-ba6b-55eb00fb6079',
    ),
  );
  $terms[] = array(
    'name' => 'New Fluke Products',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '6dade41b-8260-4bd5-8a21-9104e5770858',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'New Fluke Products',
          'format' => NULL,
          'safe_value' => 'New Fluke Products',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'new-fluke-products',
          'format' => NULL,
          'safe_value' => 'new-fluke-products',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1956,
          'revision_id' => 1956,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670344,
          'changed' => 1460670344,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Power Quality Analyzers',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 7,
    'uuid' => '6eb6bbc0-2eaf-4612-b269-3b4e0b16a618',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Power Quality Analyzers',
          'format' => NULL,
          'safe_value' => 'Power Quality Analyzers',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'power-quality-analyzers',
          'format' => NULL,
          'safe_value' => 'power-quality-analyzers',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1978,
          'revision_id' => 1978,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671091,
          'changed' => 1460671091,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'ef76bf6c-3af7-48b0-870d-4dc1a38bd673',
    ),
  );
  $terms[] = array(
    'name' => 'Battery Testers',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '70a13156-0f97-41f4-8dd2-71a6fdc8858a',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Battery Testers',
          'format' => NULL,
          'safe_value' => 'Battery Testers',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'battery-testers',
          'format' => NULL,
          'safe_value' => 'battery-testers',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1971,
          'revision_id' => 1971,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671060,
          'changed' => 1460671060,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'ef76bf6c-3af7-48b0-870d-4dc1a38bd673',
    ),
  );
  $terms[] = array(
    'name' => 'Product Registration',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 9,
    'uuid' => '72acd38c-5322-48c4-96b2-3dbbcc7f15cd',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Product Registration',
          'format' => NULL,
          'safe_value' => 'Product Registration',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'product-registration',
          'format' => NULL,
          'safe_value' => 'product-registration',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2038,
          'revision_id' => 2038,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673282,
          'changed' => 1460673282,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'mA Loop Calibrators',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => '748501c2-4b32-4c62-a032-ab0ccbb39a05',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'mA Loop Calibrators',
          'format' => NULL,
          'safe_value' => 'mA Loop Calibrators',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'ma-loop-calibrators',
          'format' => NULL,
          'safe_value' => 'ma-loop-calibrators',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1966,
          'revision_id' => 1966,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670417,
          'changed' => 1460670417,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'dffdbc8c-f9a4-47da-8e31-533d1a8d2c50',
    ),
  );
  $terms[] = array(
    'name' => 'Measurement Basics',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => '748ff66a-a303-42c9-8507-55ed5389b355',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Measurement Basics',
          'format' => NULL,
          'safe_value' => 'Measurement Basics',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'measurement-basics',
          'format' => NULL,
          'safe_value' => 'measurement-basics',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2009,
          'revision_id' => 2009,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672631,
          'changed' => 1460672631,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    ),
  );
  $terms[] = array(
    'name' => 'Integrity',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => '759d066d-5473-43aa-bbcd-f12115580e71',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Integrity',
          'format' => NULL,
          'safe_value' => 'Integrity',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'integrity',
          'format' => NULL,
          'safe_value' => 'integrity',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2028,
          'revision_id' => 2028,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673230,
          'changed' => 1460673230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e026ebfe-ee3d-468b-ba6b-55eb00fb6079',
    ),
  );
  $terms[] = array(
    'name' => 'Temperature Calibration',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => '7b00745b-9ee6-42c3-be03-7cef72743284',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Temperature Calibration',
          'format' => NULL,
          'safe_value' => 'Temperature Calibration',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'temperature-calibration',
          'format' => NULL,
          'safe_value' => 'temperature-calibration',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2015,
          'revision_id' => 2015,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672657,
          'changed' => 1460672657,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '293575ab-f1b2-4c82-a2f3-0a6f5f84ddd4',
    ),
  );
  $terms[] = array(
    'name' => 'Test Tool Catalog',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 5,
    'uuid' => '7b3c9660-33eb-4d38-ba69-db2731636948',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Test Tool Catalog',
          'format' => NULL,
          'safe_value' => 'Test Tool Catalog',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'test-tool-catalog',
          'format' => NULL,
          'safe_value' => 'test-tool-catalog',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1959,
          'revision_id' => 1959,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670357,
          'changed' => 1460670357,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Building Infrastructure',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 7,
    'uuid' => '82a14af7-0dae-4596-a26c-8a78d69b63c4',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Building Infrastructure',
          'format' => NULL,
          'safe_value' => 'Building Infrastructure',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'building-infrastructure',
          'format' => NULL,
          'safe_value' => 'building-infrastructure',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1961,
          'revision_id' => 1961,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670368,
          'changed' => 1460670368,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Electrical Safety',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 4,
    'uuid' => '8c795549-949b-4967-821e-cde0b2f8c888',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Electrical Safety',
          'format' => NULL,
          'safe_value' => 'Electrical Safety',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'electrical-safety',
          'format' => NULL,
          'safe_value' => 'electrical-safety',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2017,
          'revision_id' => 2017,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672666,
          'changed' => 1460672666,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    ),
  );
  $terms[] = array(
    'name' => 'Technical Support',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 15,
    'uuid' => '8cfa515a-4a4a-4233-acf2-4c83d2b7509e',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Technical Support',
          'format' => NULL,
          'safe_value' => 'Technical Support',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'technical-support',
          'format' => NULL,
          'safe_value' => 'technical-support',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2044,
          'revision_id' => 2044,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673310,
          'changed' => 1460673310,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Electrical Inspection',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '916a3143-a50c-4877-969b-ec92244528db',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Electrical Inspection',
          'format' => NULL,
          'safe_value' => 'Electrical Inspection',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'electrical-inspection',
          'format' => NULL,
          'safe_value' => 'electrical-inspection',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2012,
          'revision_id' => 2012,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672644,
          'changed' => 1460672644,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '293575ab-f1b2-4c82-a2f3-0a6f5f84ddd4',
    ),
  );
  $terms[] = array(
    'name' => 'Complete Your Toolbelt',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => '9c2370f9-d369-4c83-8d30-9ea7be0f6513',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Complete Your Toolbelt',
          'format' => NULL,
          'safe_value' => 'Complete Your Toolbelt',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'complete-your-toolbelt',
          'format' => NULL,
          'safe_value' => 'complete-your-toolbelt',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1955,
          'revision_id' => 1955,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670339,
          'changed' => 1460670339,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Fluke News',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '9ca7f4da-dde6-49fb-a315-be61c8da23b9',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluke News',
          'format' => NULL,
          'safe_value' => 'Fluke News',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-news',
          'format' => NULL,
          'safe_value' => 'fluke-news',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1998,
          'revision_id' => 1998,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671732,
          'changed' => 1460671732,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '232a6652-260d-4dce-8e76-d7ea8b59abf6',
    ),
  );
  $terms[] = array(
    'name' => 'Intrinsically Safe',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 12,
    'uuid' => 'a463977d-6e1f-4f9a-8bc0-a394fce30fe7',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Intrinsically Safe',
          'format' => NULL,
          'safe_value' => 'Intrinsically Safe',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'intrinsically-safe',
          'format' => NULL,
          'safe_value' => 'intrinsically-safe',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1987,
          'revision_id' => 1987,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671682,
          'changed' => 1460671682,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Training',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 100,
    'uuid' => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Training',
          'format' => NULL,
          'safe_value' => 'Training',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'training',
          'format' => NULL,
          'safe_value' => 'training',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2007,
          'revision_id' => 2007,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672623,
          'changed' => 1460672623,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Warranties',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 16,
    'uuid' => 'a866e02a-9525-4348-be9d-f5c3524c0de3',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Warranties',
          'format' => NULL,
          'safe_value' => 'Warranties',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'warranties',
          'format' => NULL,
          'safe_value' => 'warranties',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2045,
          'revision_id' => 2045,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673315,
          'changed' => 1460673315,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Fluke Gear',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => 'a8a0b0b7-05e9-4a77-b894-d57b2d566010',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluke Gear',
          'format' => NULL,
          'safe_value' => 'Fluke Gear',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-gear',
          'format' => NULL,
          'safe_value' => 'fluke-gear',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2050,
          'revision_id' => 2050,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673444,
          'changed' => 1460673444,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '32d7b57f-8694-494d-856f-d26348fb6153',
    ),
  );
  $terms[] = array(
    'name' => 'Webinars',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 6,
    'uuid' => 'afa648b4-cbbe-42ed-ae80-d985011dd85d',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Webinars',
          'format' => NULL,
          'safe_value' => 'Webinars',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'webinars',
          'format' => NULL,
          'safe_value' => 'webinars',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2019,
          'revision_id' => 2019,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672674,
          'changed' => 1460672674,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'a5f6db71-a225-4b9d-bd99-6a6e0b56b0d4',
    ),
  );
  $terms[] = array(
    'name' => 'Fluke Connect Assets',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => 'b078dbfa-a139-4f41-8fd0-4994d0fd1e49',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluke Connect Assets',
          'format' => NULL,
          'safe_value' => 'Fluke Connect Assets',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-connect-assets',
          'format' => NULL,
          'safe_value' => 'fluke-connect-assets',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1985,
          'revision_id' => 1985,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671126,
          'changed' => 1460671126,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '66ad3207-bdf2-4d67-bbae-4445f634da7b',
    ),
  );
  $terms[] = array(
    'name' => 'Safety',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 4,
    'uuid' => 'b0dfbc3f-b0e5-48be-b16a-429b23787094',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Safety',
          'format' => NULL,
          'safe_value' => 'Safety',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'safety',
          'format' => NULL,
          'safe_value' => 'safety',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2006,
          'revision_id' => 2006,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671765,
          'changed' => 1460671765,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '232a6652-260d-4dce-8e76-d7ea8b59abf6',
    ),
  );
  $terms[] = array(
    'name' => 'Laser Distance Meters',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => 'b3720202-d7c9-4f01-b2f7-8e6c047bd94c',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Laser Distance Meters',
          'format' => NULL,
          'safe_value' => 'Laser Distance Meters',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'laser-distance-meters',
          'format' => NULL,
          'safe_value' => 'laser-distance-meters',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1964,
          'revision_id' => 1964,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670383,
          'changed' => 1460670383,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '82a14af7-0dae-4596-a26c-8a78d69b63c4',
    ),
  );
  $terms[] = array(
    'name' => 'Awards',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => 'b3873ff0-4b5d-413c-9435-4714b330c9ec',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Awards',
          'format' => NULL,
          'safe_value' => 'Awards',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'awards',
          'format' => NULL,
          'safe_value' => 'awards',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1954,
          'revision_id' => 1954,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670335,
          'changed' => 1460670335,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Vibration Analysis',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => 'b8772605-d6c0-4d3a-bec9-41e30de38c54',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Vibration Analysis',
          'format' => NULL,
          'safe_value' => 'Vibration Analysis',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'vibration-analysis',
          'format' => NULL,
          'safe_value' => 'vibration-analysis',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1990,
          'revision_id' => 1990,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671695,
          'changed' => 1460671695,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '5c13d9d0-5aac-4730-ae64-365830156e8c',
    ),
  );
  $terms[] = array(
    'name' => 'Press Releases',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 8,
    'uuid' => 'be9272e7-184e-449f-ab86-7edea7b30c3f',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Press Releases',
          'format' => NULL,
          'safe_value' => 'Press Releases',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'press-releases',
          'format' => NULL,
          'safe_value' => 'press-releases',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2037,
          'revision_id' => 2037,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673277,
          'changed' => 1460673277,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Fluke Accessories',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => 'c0d0f754-b3f9-40d7-ac77-de59896a07b5',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluke Accessories',
          'format' => NULL,
          'safe_value' => 'Fluke Accessories',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-accessories',
          'format' => NULL,
          'safe_value' => 'fluke-accessories',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2048,
          'revision_id' => 2048,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673436,
          'changed' => 1460673436,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '32d7b57f-8694-494d-856f-d26348fb6153',
    ),
  );
  $terms[] = array(
    'name' => 'Service Center Locations',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 13,
    'uuid' => 'c77a5e13-d09e-49f9-9c1f-eeaa594817cc',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Service Center Locations',
          'format' => NULL,
          'safe_value' => 'Service Center Locations',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'service-center-locations',
          'format' => NULL,
          'safe_value' => 'service-center-locations',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2042,
          'revision_id' => 2042,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673300,
          'changed' => 1460673300,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Clamp Meters',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => 'c880079a-aebb-41eb-b25f-8b2d1d3b731a',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Clamp Meters',
          'format' => NULL,
          'safe_value' => 'Clamp Meters',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'clamp-meters',
          'format' => NULL,
          'safe_value' => 'clamp-meters',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1972,
          'revision_id' => 1972,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671065,
          'changed' => 1460671065,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'ef76bf6c-3af7-48b0-870d-4dc1a38bd673',
    ),
  );
  $terms[] = array(
    'name' => 'Fluke Smartview®',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => 'c9f31916-a267-4cf3-b708-e749773bb5e8',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluke Smartview®',
          'format' => NULL,
          'safe_value' => 'Fluke Smartview®',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-smartview',
          'format' => NULL,
          'safe_value' => 'fluke-smartview',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1986,
          'revision_id' => 1986,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671122,
          'changed' => 1460671122,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '66ad3207-bdf2-4d67-bbae-4445f634da7b',
    ),
  );
  $terms[] = array(
    'name' => 'Accreditation',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => 'ce1b261b-fc67-4dbb-a56a-46ee769fc72d',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Accreditation',
          'format' => NULL,
          'safe_value' => 'Accreditation',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'accreditation',
          'format' => NULL,
          'safe_value' => 'accreditation',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2030,
          'revision_id' => 2030,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673245,
          'changed' => 1460673245,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Return Materials Authorization',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 11,
    'uuid' => 'cf603dd0-8233-432a-80dc-22efef6a7949',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Return Materials Authorization',
          'format' => NULL,
          'safe_value' => 'Return Materials Authorization',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'return-materials-authorization',
          'format' => NULL,
          'safe_value' => 'return-materials-authorization',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2040,
          'revision_id' => 2040,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673291,
          'changed' => 1460673291,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Fluke Calibration Software',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => 'd2b79e5d-9217-4366-9645-2e0746ed1bea',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluke Calibration Software',
          'format' => NULL,
          'safe_value' => 'Fluke Calibration Software',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-calibration-software',
          'format' => NULL,
          'safe_value' => 'fluke-calibration-software',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1984,
          'revision_id' => 1984,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671118,
          'changed' => 1460671118,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '66ad3207-bdf2-4d67-bbae-4445f634da7b',
    ),
  );
  $terms[] = array(
    'name' => 'Factory Reconditioned',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => 'd511d1fd-33a9-4b50-b7de-1f4d14316fb2',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Factory Reconditioned',
          'format' => NULL,
          'safe_value' => 'Factory Reconditioned',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'factory-reconditioned',
          'format' => NULL,
          'safe_value' => 'factory-reconditioned',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2049,
          'revision_id' => 2049,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673440,
          'changed' => 1460673440,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '32d7b57f-8694-494d-856f-d26348fb6153',
    ),
  );
  $terms[] = array(
    'name' => 'Fluke View Forms',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 5,
    'uuid' => 'd5339931-636b-4990-aac0-7bd6a87707f8',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluke View Forms',
          'format' => NULL,
          'safe_value' => 'Fluke View Forms',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluke-view-forms',
          'format' => NULL,
          'safe_value' => 'fluke-view-forms',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2034,
          'revision_id' => 2034,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673264,
          'changed' => 1460673264,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Infrared Cameras',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => 'd60be211-ebc5-4625-ac48-30e79a6f6bfb',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Infrared Cameras',
          'format' => NULL,
          'safe_value' => 'Infrared Cameras',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'infrared-cameras',
          'format' => NULL,
          'safe_value' => 'infrared-cameras',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1992,
          'revision_id' => 1992,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671704,
          'changed' => 1460671704,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e70dab3b-950d-459d-9cae-bc734e5491ff',
    ),
  );
  $terms[] = array(
    'name' => 'Electronics Testing',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 10,
    'uuid' => 'dc023e36-ece5-48aa-b2d6-297a81567619',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Electronics Testing',
          'format' => NULL,
          'safe_value' => 'Electronics Testing',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'electronics-testing',
          'format' => NULL,
          'safe_value' => 'electronics-testing',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1979,
          'revision_id' => 1979,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671096,
          'changed' => 1460671096,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Calibration Tools',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 8,
    'uuid' => 'dffdbc8c-f9a4-47da-8e31-533d1a8d2c50',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Calibration Tools',
          'format' => NULL,
          'safe_value' => 'Calibration Tools',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'calibration-tools',
          'format' => NULL,
          'safe_value' => 'calibration-tools',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1965,
          'revision_id' => 1965,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670388,
          'changed' => 1460670388,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'About Us',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => 'e026ebfe-ee3d-468b-ba6b-55eb00fb6079',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'About Us',
          'format' => NULL,
          'safe_value' => 'About Us',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'about-us',
          'format' => NULL,
          'safe_value' => 'about-us',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2024,
          'revision_id' => 2024,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672696,
          'changed' => 1460672696,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Calibration Services',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => 'e51611a7-2a28-429e-9103-38186c40cdd4',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Calibration Services',
          'format' => NULL,
          'safe_value' => 'Calibration Services',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'calibration-services',
          'format' => NULL,
          'safe_value' => 'calibration-services',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2031,
          'revision_id' => 2031,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673250,
          'changed' => 1460673250,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Fluid Systems',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => 'e674fc3a-86b1-4a61-8903-3c9e43e2d3ec',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Fluid Systems',
          'format' => NULL,
          'safe_value' => 'Fluid Systems',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'fluid-systems',
          'format' => NULL,
          'safe_value' => 'fluid-systems',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2013,
          'revision_id' => 2013,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460672648,
          'changed' => 1460672648,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '293575ab-f1b2-4c82-a2f3-0a6f5f84ddd4',
    ),
  );
  $terms[] = array(
    'name' => 'Temperature Measurement',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 18,
    'uuid' => 'e70dab3b-950d-459d-9cae-bc734e5491ff',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Temperature Measurement',
          'format' => NULL,
          'safe_value' => 'Temperature Measurement',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'temperature-measurement',
          'format' => NULL,
          'safe_value' => 'temperature-measurement',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1991,
          'revision_id' => 1991,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671700,
          'changed' => 1460671700,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'CarePlans',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => 'eeab0c57-88e1-4dde-90a2-7e610274b9e8',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'CarePlans',
          'format' => NULL,
          'safe_value' => 'CarePlans',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'careplans',
          'format' => NULL,
          'safe_value' => 'careplans',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2032,
          'revision_id' => 2032,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673254,
          'changed' => 1460673254,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Electrical Testing',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 9,
    'uuid' => 'ef76bf6c-3af7-48b0-870d-4dc1a38bd673',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Electrical Testing',
          'format' => NULL,
          'safe_value' => 'Electrical Testing',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'electrical-testing',
          'format' => NULL,
          'safe_value' => 'electrical-testing',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1970,
          'revision_id' => 1970,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671056,
          'changed' => 1460671056,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Indoor Air Quality Testing',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => 'f15beaba-a4fa-4927-a403-cb75e0e04a6a',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Indoor Air Quality Testing',
          'format' => NULL,
          'safe_value' => 'Indoor Air Quality Testing',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'indoor-air-quality-testing',
          'format' => NULL,
          'safe_value' => 'indoor-air-quality-testing',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1963,
          'revision_id' => 1963,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670378,
          'changed' => 1460670378,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '82a14af7-0dae-4596-a26c-8a78d69b63c4',
    ),
  );
  $terms[] = array(
    'name' => 'Repair',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 10,
    'uuid' => 'f4b9edeb-cdf7-4367-8d9d-ff94395fcdc8',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Repair',
          'format' => NULL,
          'safe_value' => 'Repair',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'repair',
          'format' => NULL,
          'safe_value' => 'repair',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2039,
          'revision_id' => 2039,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460673286,
          'changed' => 1460673286,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '691d7bb7-7eaa-418d-a877-c10d73605756',
    ),
  );
  $terms[] = array(
    'name' => 'Installation testers',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 14,
    'uuid' => 'f6859846-5a03-4343-afe2-5798458aff42',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-gb' => array(
        0 => array(
          'value' => 'Installation testers',
          'format' => NULL,
          'safe_value' => 'Installation testers',
        ),
      ),
      'en-in' => array(
        0 => array(
          'value' => 'Installation testers',
          'format' => NULL,
          'safe_value' => 'Installation testers',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-gb' => array(
        0 => array(
          'value' => 'installation-testers',
          'format' => NULL,
          'safe_value' => 'installation-testers',
        ),
      ),
      'en-in' => array(
        0 => array(
          'value' => 'installation-testers',
          'format' => NULL,
          'safe_value' => 'installation-testers',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-gb',
      'data' => array(
        'en-gb' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2409,
          'revision_id' => 2409,
          'language' => 'en-gb',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1461365277,
          'changed' => 1461365277,
          'blocking' => 0,
        ),
        'en-in' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2409,
          'revision_id' => 2409,
          'language' => 'en-in',
          'source' => 'en-gb',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1461365326,
          'changed' => 1461365466,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    ),
  );
  $terms[] = array(
    'name' => 'Portable Oscilloscopes',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => 'f945c841-cee9-46be-96e4-6b9450f8f921',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Portable Oscilloscopes',
          'format' => NULL,
          'safe_value' => 'Portable Oscilloscopes',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'portable-oscilloscopes',
          'format' => NULL,
          'safe_value' => 'portable-oscilloscopes',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1982,
          'revision_id' => 1982,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671109,
          'changed' => 1460671109,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'dc023e36-ece5-48aa-b2d6-297a81567619',
    ),
  );
  $terms[] = array(
    'name' => 'HVAC Tools',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => 'fa7d5fe2-79df-4e3d-803e-a47a9c265627',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'HVAC Tools',
          'format' => NULL,
          'safe_value' => 'HVAC Tools',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'hvac-tools',
          'format' => NULL,
          'safe_value' => 'hvac-tools',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1962,
          'revision_id' => 1962,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460670372,
          'changed' => 1460670372,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '82a14af7-0dae-4596-a26c-8a78d69b63c4',
    ),
  );
  $terms[] = array(
    'name' => 'Chemical Processing',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => 'fac9a8d8-eba1-4da6-9483-1d369cc8ffda',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Chemical Processing',
          'format' => NULL,
          'safe_value' => 'Chemical Processing',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'chemical-processing',
          'format' => NULL,
          'safe_value' => 'chemical-processing',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 2001,
          'revision_id' => 2001,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671752,
          'changed' => 1460671752,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '32c47502-3003-4b6d-a999-8da0478755be',
    ),
  );
  $terms[] = array(
    'name' => 'Electrical Testers',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 4,
    'uuid' => 'fc4116b0-5ae8-479d-92c2-17e4ccdc5f19',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'Electrical Testers',
          'format' => NULL,
          'safe_value' => 'Electrical Testers',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-us' => array(
        0 => array(
          'value' => 'electrical-testers',
          'format' => NULL,
          'safe_value' => 'electrical-testers',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1975,
          'revision_id' => 1975,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460671077,
          'changed' => 1460671077,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'ef76bf6c-3af7-48b0-870d-4dc1a38bd673',
    ),
  );
  $terms[] = array(
    'name' => 'Products',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 93,
    'uuid' => 'fe75e206-fe44-4aa6-bc7f-65e47f65f38c',
    'vocabulary_machine_name' => 'main_menu',
    'field_content_title' => array(
      'en-ie' => array(
        0 => array(
          'value' => 'Products',
          'format' => NULL,
          'safe_value' => 'Products',
        ),
      ),
      'en-us' => array(
        0 => array(
          'value' => 'Products',
          'format' => NULL,
          'safe_value' => 'Products',
        ),
      ),
    ),
    'field_url_title' => array(
      'en-ie' => array(
        0 => array(
          'value' => 'products',
          'format' => NULL,
          'safe_value' => 'products',
        ),
      ),
      'en-us' => array(
        0 => array(
          'value' => 'products',
          'format' => NULL,
          'safe_value' => 'products',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1953,
          'revision_id' => 1953,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460669738,
          'changed' => 1460669738,
          'blocking' => 0,
        ),
        'en-ie' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1953,
          'revision_id' => 1953,
          'language' => 'en-ie',
          'source' => 'en-us',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460669795,
          'changed' => 1460669795,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  return $terms;
}
