<?php
/**
 * @file
 * tax_meas_energy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_meas_energy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Mains signaling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '41725406-7b86-46ea-b9a4-0e59097888c8',
    'vocabulary_machine_name' => 'energy',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1787,
          'revision_id' => 1787,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413185,
          'changed' => 1460413185,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Transient capture',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5574d54b-180d-4902-a3fc-5870b66088df',
    'vocabulary_machine_name' => 'energy',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1789,
          'revision_id' => 1789,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413185,
          'changed' => 1460413185,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Flicker',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5c9e77f5-5327-4c6e-a518-b22f229d4bfa',
    'vocabulary_machine_name' => 'energy',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1783,
          'revision_id' => 1783,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413185,
          'changed' => 1460413185,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Energy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5e69d7f1-b003-4510-9b65-915ca6d02684',
    'vocabulary_machine_name' => 'energy',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1785,
          'revision_id' => 1785,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413185,
          'changed' => 1460413185,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Interharmonics',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '68372250-9e5f-4789-b396-1dcc3c99598c',
    'vocabulary_machine_name' => 'energy',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1780,
          'revision_id' => 1780,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413185,
          'changed' => 1460413185,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Phase sequence components',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '70c49d55-7179-45cf-8fcf-79339f9bc38c',
    'vocabulary_machine_name' => 'energy',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1781,
          'revision_id' => 1781,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413185,
          'changed' => 1460413185,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'IEC61000-4-30 class A',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e5ca18f-2b18-4a35-933b-1819c791f274',
    'vocabulary_machine_name' => 'energy',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1788,
          'revision_id' => 1788,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413185,
          'changed' => 1460413185,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Energy aggregation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c296116a-a5ad-4cb7-9170-ae032b481727',
    'vocabulary_machine_name' => 'energy',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1786,
          'revision_id' => 1786,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413185,
          'changed' => 1460413185,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'EN50160 analysis',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c9000a61-9b3e-4be5-b0ed-50fb9dcea41e',
    'vocabulary_machine_name' => 'energy',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1784,
          'revision_id' => 1784,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413185,
          'changed' => 1460413185,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Phasor diagram',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f7c17ab8-d26d-406d-b724-ce4e63e88ea9',
    'vocabulary_machine_name' => 'energy',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1782,
          'revision_id' => 1782,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413185,
          'changed' => 1460413185,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  return $terms;
}
