<?php
/**
 * @file
 * tax_meas_temp.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_meas_temp_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => '0 C / 32 F',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => '3e8348a2-af43-49be-8acf-17004b6eded9',
    'vocabulary_machine_name' => 'temperature',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1928,
          'revision_id' => 1928,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498276,
          'changed' => 1460498276,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '8264a147-6756-40cf-bec0-bf0d82779e0e',
    ),
  );
  $terms[] = array(
    'name' => 'Type of measurement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 6,
    'uuid' => '4da2f5f8-e664-4131-a504-a32a96e74900',
    'vocabulary_machine_name' => 'temperature',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1856,
          'revision_id' => 1856,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460414174,
          'changed' => 1460414174,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Contact',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '779a46d2-6906-4dd0-98aa-8741e7e201cb',
    'vocabulary_machine_name' => 'temperature',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1925,
          'revision_id' => 1925,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498114,
          'changed' => 1460498114,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '4da2f5f8-e664-4131-a504-a32a96e74900',
    ),
  );
  $terms[] = array(
    'name' => 'Temperature',
    'description' => NULL,
    'format' => NULL,
    'weight' => 7,
    'uuid' => '8264a147-6756-40cf-bec0-bf0d82779e0e',
    'vocabulary_machine_name' => 'temperature',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1857,
          'revision_id' => 1857,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460414174,
          'changed' => 1460414174,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Temperature simulation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 9,
    'uuid' => '87d59230-b55c-4492-999e-6f95387adb83',
    'vocabulary_machine_name' => 'temperature',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1858,
          'revision_id' => 1858,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460414174,
          'changed' => 1460414174,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Temperature sourcing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 5,
    'uuid' => '8d74e9e1-d4a7-4a3e-9e72-04745ff9647b',
    'vocabulary_machine_name' => 'temperature',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1859,
          'revision_id' => 1859,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460414174,
          'changed' => 1460414174,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '900 C / 1652 F',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '8fdc6f7a-9acf-4421-bedd-5028f30278ac',
    'vocabulary_machine_name' => 'temperature',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1929,
          'revision_id' => 1929,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498291,
          'changed' => 1460498291,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '8264a147-6756-40cf-bec0-bf0d82779e0e',
    ),
  );
  $terms[] = array(
    'name' => 'Non-contact',
    'description' => NULL,
    'format' => NULL,
    'weight' => 1,
    'uuid' => 'a0308e41-1b93-409a-99a6-bec139d2861e',
    'vocabulary_machine_name' => 'temperature',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1926,
          'revision_id' => 1926,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498114,
          'changed' => 1460498114,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '4da2f5f8-e664-4131-a504-a32a96e74900',
    ),
  );
  $terms[] = array(
    'name' => '-40 C / -40 F',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => 'd6cb627f-0782-4cca-a2ef-8c4d8aa53cff',
    'vocabulary_machine_name' => 'temperature',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1927,
          'revision_id' => 1927,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460498255,
          'changed' => 1460498255,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '8264a147-6756-40cf-bec0-bf0d82779e0e',
    ),
  );
  $terms[] = array(
    'name' => 'Infrared temperature source',
    'description' => NULL,
    'format' => NULL,
    'weight' => 8,
    'uuid' => 'e7b11443-83c0-4ce0-8234-9c8e2aff786e',
    'vocabulary_machine_name' => 'temperature',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1860,
          'revision_id' => 1860,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460414174,
          'changed' => 1460414174,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  return $terms;
}
