<?php
/**
 * @file
 * tax_opco.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_opco_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => "Fluke Industrial Group",
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '09654f29-7445-4ece-9069-e83ba93c78ad',
    'vocabulary_machine_name' => 'opco',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Fluke Industrial Group',
    'entity_translation_handler_id' => 'taxonomy_term-eid-707-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 707,
          'revision_id' => 707,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459979503,
          'changed' => 1459979503,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Fluke Calibration",
    'description' => NULL,
    'format' => NULL,
    'weight' => 4,
    'uuid' => '602bbb81-3b25-48d0-b3fe-8ac6ba82a8ba',
    'vocabulary_machine_name' => 'opco',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Fluke Calibration',
    'entity_translation_handler_id' => 'taxonomy_term-eid-708-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 708,
          'revision_id' => 708,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459979509,
          'changed' => 1459979509,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Fluke T & M",
    'description' => NULL,
    'format' => NULL,
    'weight' => 5,
    'uuid' => '819754f9-e962-469a-8fcb-43a2df6b2f2d',
    'vocabulary_machine_name' => 'opco',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Fluke T & M',
    'entity_translation_handler_id' => 'taxonomy_term-eid-709-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 709,
          'revision_id' => 709,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459979511,
          'changed' => 1459979511,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Pomona",
    'description' => NULL,
    'format' => NULL,
    'weight' => 6,
    'uuid' => 'b5f62a2e-cfff-4490-be0b-27b3e882d2cc',
    'vocabulary_machine_name' => 'opco',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Pomona',
    'entity_translation_handler_id' => 'taxonomy_term-eid-710-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 710,
          'revision_id' => 710,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459979514,
          'changed' => 1459979514,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Beha-Amprobe",
    'description' => NULL,
    'format' => NULL,
    'weight' => 2,
    'uuid' => 'da7ca6b4-d649-40ad-8397-10a59d11a7ac',
    'vocabulary_machine_name' => 'opco',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Beha-Amprobe',
    'entity_translation_handler_id' => 'taxonomy_term-eid-975-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 975,
          'revision_id' => 975,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459979516,
          'changed' => 1459979516,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Amprobe",
    'description' => NULL,
    'format' => NULL,
    'weight' => 1,
    'uuid' => 'df7bd0b5-5d46-4489-b17a-a11af55e390b',
    'vocabulary_machine_name' => 'opco',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Amprobe',
    'entity_translation_handler_id' => 'taxonomy_term-eid-711-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 711,
          'revision_id' => 711,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459979516,
          'changed' => 1459979516,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Fluke BioMed",
    'description' => NULL,
    'format' => NULL,
    'weight' => 3,
    'uuid' => 'e3dbadef-9e62-4b7b-aa37-7ee04cd41e40',
    'vocabulary_machine_name' => 'opco',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Fluke BioMed',
    'entity_translation_handler_id' => 'taxonomy_term-eid-712-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 712,
          'revision_id' => 712,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459979517,
          'changed' => 1459979517,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  return $terms;
}
