<?php
/**
 * @file
 * tax_meas_therm.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_meas_therm_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'J-type',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0a4751cd-98ea-4d8a-aaf6-59b5caf60695',
    'vocabulary_machine_name' => 'thermocouples',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1724,
          'revision_id' => 1724,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412942,
          'changed' => 1460412942,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'R-type',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2055744e-55bb-45c0-a6b0-449a19527aa6',
    'vocabulary_machine_name' => 'thermocouples',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1726,
          'revision_id' => 1726,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412942,
          'changed' => 1460412942,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'K-type',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3e93f5d3-af9d-4557-9740-57d2ccae78ed',
    'vocabulary_machine_name' => 'thermocouples',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1725,
          'revision_id' => 1725,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412942,
          'changed' => 1460412942,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'S-type',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4b8c8501-b09d-41e1-bfce-0072e307f89d',
    'vocabulary_machine_name' => 'thermocouples',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1727,
          'revision_id' => 1727,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412942,
          'changed' => 1460412942,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'E-type',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8a0e5a56-5abb-4248-b6f5-1dc2d750c0dc',
    'vocabulary_machine_name' => 'thermocouples',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1729,
          'revision_id' => 1729,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412942,
          'changed' => 1460412942,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'T-type',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'da751923-c3d7-40d5-868b-d3acf82c0d6a',
    'vocabulary_machine_name' => 'thermocouples',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1728,
          'revision_id' => 1728,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412942,
          'changed' => 1460412942,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'N-type',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f278e4f7-9520-492f-9e14-2b3b2fbe22f0',
    'vocabulary_machine_name' => 'thermocouples',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1723,
          'revision_id' => 1723,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412942,
          'changed' => 1460412942,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  return $terms;
}
