<?php
/**
 * @file
 * tax_event.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_event_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => "Seminar",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 2,
    'uuid' => '087d1942-1853-4d31-85fd-90873c5a972d',
    'vocabulary_machine_name' => 'events',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Seminar',
    'entity_translation_handler_id' => 'taxonomy_term-eid-682-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 682,
          'revision_id' => 682,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459967534,
          'changed' => 1459967534,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Workshop",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 1,
    'uuid' => '2c6d1b04-37f1-48f6-a862-9d434cfd383f',
    'vocabulary_machine_name' => 'events',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Workshop',
    'entity_translation_handler_id' => 'taxonomy_term-eid-681-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 681,
          'revision_id' => 681,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459967536,
          'changed' => 1459967536,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Tradeshow",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '2dae5b94-8bdf-421f-bd72-1ae2e58ebc83',
    'vocabulary_machine_name' => 'events',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Tradeshow',
    'entity_translation_handler_id' => 'taxonomy_term-eid-680-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 680,
          'revision_id' => 680,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459967536,
          'changed' => 1459967536,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Live Webinar',
    'entity_translation_handler_id' ",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 4,
    'uuid' => '58edc139-268e-43df-8c55-47f98d1b3c8c',
    'vocabulary_machine_name' => 'events',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Live Webinar',
    'entity_translation_handler_id' => 'taxonomy_term-eid-684-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 684,
          'revision_id' => 684,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459967537,
          'changed' => 1459967537,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Motors and Drives",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 5,
    'uuid' => '8ff55a91-9808-4048-9638-221e90555c70',
    'vocabulary_machine_name' => 'events',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Motors and Drives',
    'entity_translation_handler_id' => 'taxonomy_term-eid-101-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 101,
          'revision_id' => 101,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459967540,
          'changed' => 1459967540,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Proactive Maintenance and Thermography Seminars",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 6,
    'uuid' => 'c132b7b7-0fca-4a64-8bcc-96208ddf93bf',
    'vocabulary_machine_name' => 'events',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Proactive Maintenance and Thermography Seminars',
    'entity_translation_handler_id' => 'taxonomy_term-eid-100-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 100,
          'revision_id' => 100,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459967541,
          'changed' => 1459967541,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Training Course",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 3,
    'uuid' => 'e813e83b-5ad3-4dd3-88d2-46bfb6593338',
    'vocabulary_machine_name' => 'events',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Training Course',
    'entity_translation_handler_id' => 'taxonomy_term-eid-683-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 683,
          'revision_id' => 683,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459967543,
          'changed' => 1459967543,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  return $terms;
}
