<?php
/**
 * @file
 * tax_meas_phys.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_meas_phys_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 0,
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '133803bf-da2e-4587-b4df-c0007785f8ba',
    'vocabulary_machine_name' => 'physical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1875,
          'revision_id' => 1875,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460496569,
          'changed' => 1460496569,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fb345ce6-d923-4957-878b-d3eb91c84b5d',
    ),
  );
  $terms[] = array(
    'name' => '330 ft',
    'description' => NULL,
    'format' => NULL,
    'weight' => 3,
    'uuid' => '24e12a0f-885d-4c30-8e16-fe7afb41a942',
    'vocabulary_machine_name' => 'physical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1878,
          'revision_id' => 1878,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460496569,
          'changed' => 1460496569,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fb345ce6-d923-4957-878b-d3eb91c84b5d',
    ),
  );
  $terms[] = array(
    'name' => '165 ft',
    'description' => NULL,
    'format' => NULL,
    'weight' => 1,
    'uuid' => '3d9fcf5b-46d7-462f-86d2-fcffd5a58661',
    'vocabulary_machine_name' => 'physical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1876,
          'revision_id' => 1876,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460496569,
          'changed' => 1460496569,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fb345ce6-d923-4957-878b-d3eb91c84b5d',
    ),
  );
  $terms[] = array(
    'name' => '260 ft',
    'description' => NULL,
    'format' => NULL,
    'weight' => 2,
    'uuid' => '42184da1-70f7-4cc7-9948-13203a19d6ec',
    'vocabulary_machine_name' => 'physical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1877,
          'revision_id' => 1877,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460496569,
          'changed' => 1460496569,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'fb345ce6-d923-4957-878b-d3eb91c84b5d',
    ),
  );
  $terms[] = array(
    'name' => 'Angle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '817e27cc-181f-47d5-8f3a-33a0a7aab5bc',
    'vocabulary_machine_name' => 'physical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1735,
          'revision_id' => 1735,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412981,
          'changed' => 1460412981,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Volume',
    'description' => NULL,
    'format' => NULL,
    'weight' => 4,
    'uuid' => '86f6fd24-82d4-4ad1-ae9b-98685dbe6648',
    'vocabulary_machine_name' => 'physical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1737,
          'revision_id' => 1737,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412981,
          'changed' => 1460412981,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'RPM',
    'description' => NULL,
    'format' => NULL,
    'weight' => 3,
    'uuid' => 'ec35cd7b-fa4c-460f-9f9b-2b46077225db',
    'vocabulary_machine_name' => 'physical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1736,
          'revision_id' => 1736,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412981,
          'changed' => 1460412981,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Height',
    'description' => NULL,
    'format' => NULL,
    'weight' => 2,
    'uuid' => 'f11be694-0fa8-4446-8f96-78378c9fa271',
    'vocabulary_machine_name' => 'physical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1734,
          'revision_id' => 1734,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412981,
          'changed' => 1460412981,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Distance',
    'description' => NULL,
    'format' => NULL,
    'weight' => 1,
    'uuid' => 'fb345ce6-d923-4957-878b-d3eb91c84b5d',
    'vocabulary_machine_name' => 'physical',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1733,
          'revision_id' => 1733,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460412981,
          'changed' => 1460412981,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  return $terms;
}
