<?php
/**
 * @file
 * tax_year.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_year_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 2002,
    'description' => NULL,
    'format' => NULL,
    'weight' => 14,
    'uuid' => '0b4e5795-e786-40aa-9341-9139adc1ff82',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2002,
    'entity_translation_handler_id' => 'taxonomy_term-eid-904-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 904,
          'revision_id' => 904,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982043,
          'changed' => 1459982043,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2001,
    'description' => NULL,
    'format' => NULL,
    'weight' => 15,
    'uuid' => '0c408651-9650-49fc-9982-7db3ccf004a2',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2001,
    'entity_translation_handler_id' => 'taxonomy_term-eid-905-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 905,
          'revision_id' => 905,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982043,
          'changed' => 1459982043,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2009,
    'description' => NULL,
    'format' => NULL,
    'weight' => 7,
    'uuid' => '3e2d944b-71cc-4147-a353-2764aec79f9f',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2009,
    'entity_translation_handler_id' => 'taxonomy_term-eid-897-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 897,
          'revision_id' => 897,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982049,
          'changed' => 1459982049,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 1992,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 21,
    'uuid' => '54a6b40b-16a3-4dca-bf25-babcf1ba1344',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 1992,
    'entity_translation_handler_id' => 'taxonomy_term-eid-1167-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1167,
          'revision_id' => 1167,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982052,
          'changed' => 1459982052,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2011,
    'description' => NULL,
    'format' => NULL,
    'weight' => 5,
    'uuid' => '569cbf2e-967c-42bc-931b-9d734be96f8d',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2011,
    'entity_translation_handler_id' => 'taxonomy_term-eid-895-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 895,
          'revision_id' => 895,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982052,
          'changed' => 1459982052,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2005,
    'description' => NULL,
    'format' => NULL,
    'weight' => 11,
    'uuid' => '5e77f424-e76a-4831-b165-33d9bf50e81a',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2005,
    'entity_translation_handler_id' => 'taxonomy_term-eid-901-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 901,
          'revision_id' => 901,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982052,
          'changed' => 1459982052,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 1994,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 20,
    'uuid' => '690d1389-96b9-44db-8f29-b350763db31b',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 1994,
    'entity_translation_handler_id' => 'taxonomy_term-eid-1168-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1168,
          'revision_id' => 1168,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982054,
          'changed' => 1459982054,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 1974,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 25,
    'uuid' => '7eef8100-5b52-4184-9a5b-734509ec4cbd',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 1974,
    'entity_translation_handler_id' => 'taxonomy_term-eid-1163-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1163,
          'revision_id' => 1163,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982054,
          'changed' => 1459982054,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 1986,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 23,
    'uuid' => 'a6bd231b-3c2e-4384-9e77-78e7808de818',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 1986,
    'entity_translation_handler_id' => 'taxonomy_term-eid-1165-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1165,
          'revision_id' => 1165,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982057,
          'changed' => 1459982057,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2014,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 2,
    'uuid' => 'a8c2a384-054a-4213-9a67-b6e102f44a2c',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 2014,
    'entity_translation_handler_id' => 'taxonomy_term-eid-863-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 863,
          'revision_id' => 863,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982057,
          'changed' => 1459982057,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 1995,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 19,
    'uuid' => 'a9363f2e-e4aa-4745-90b3-58b8fea4f121',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 1995,
    'entity_translation_handler_id' => 'taxonomy_term-eid-1169-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1169,
          'revision_id' => 1169,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982057,
          'changed' => 1459982057,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2000,
    'description' => NULL,
    'format' => NULL,
    'weight' => 16,
    'uuid' => 'ae9e23d3-339f-4782-8591-58b32bb19b72',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2000,
    'entity_translation_handler_id' => 'taxonomy_term-eid-906-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 906,
          'revision_id' => 906,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982059,
          'changed' => 1459982059,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2016,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => 'b6fcb576-60de-4554-ac2b-74a9ecf92aba',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 2016,
    'entity_translation_handler_id' => 'taxonomy_term-eid-865-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 865,
          'revision_id' => 865,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982059,
          'changed' => 1459982059,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2004,
    'description' => NULL,
    'format' => NULL,
    'weight' => 12,
    'uuid' => 'bc5f4cec-6fe2-4530-b385-60ff001bec85',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2004,
    'entity_translation_handler_id' => 'taxonomy_term-eid-902-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 902,
          'revision_id' => 902,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982059,
          'changed' => 1459982059,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 1999,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 17,
    'uuid' => 'c78956e5-adbb-47ab-9760-db42d6e09cea',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 1999,
    'entity_translation_handler_id' => 'taxonomy_term-eid-1171-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1171,
          'revision_id' => 1171,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982060,
          'changed' => 1459982060,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2015,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 1,
    'uuid' => 'c87a6490-bae2-4f80-bb5c-b5fba2a37e23',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 2015,
    'entity_translation_handler_id' => 'taxonomy_term-eid-862-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 862,
          'revision_id' => 862,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982060,
          'changed' => 1459982060,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2013,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 3,
    'uuid' => 'c89cc50a-26b4-4b97-b9a1-28f72287a7ba',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 2013,
    'entity_translation_handler_id' => 'taxonomy_term-eid-864-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 864,
          'revision_id' => 864,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982060,
          'changed' => 1459982060,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 1981,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 24,
    'uuid' => 'd2123167-3805-4799-89b6-14c600f50a44',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 1981,
    'entity_translation_handler_id' => 'taxonomy_term-eid-1164-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1164,
          'revision_id' => 1164,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982060,
          'changed' => 1459982060,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2006,
    'description' => NULL,
    'format' => NULL,
    'weight' => 10,
    'uuid' => 'da3ef275-3efc-40bb-a9c5-1a2df5d51779',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2006,
    'entity_translation_handler_id' => 'taxonomy_term-eid-900-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 900,
          'revision_id' => 900,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982062,
          'changed' => 1459982062,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2008,
    'description' => NULL,
    'format' => NULL,
    'weight' => 8,
    'uuid' => 'da6746af-ae0e-4443-a19c-bfb4aceb34b8',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2008,
    'entity_translation_handler_id' => 'taxonomy_term-eid-898-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 898,
          'revision_id' => 898,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982062,
          'changed' => 1459982062,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2010,
    'description' => NULL,
    'format' => NULL,
    'weight' => 6,
    'uuid' => 'e08f0014-65f7-4aba-a1f8-9f099ac72dd4',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2010,
    'entity_translation_handler_id' => 'taxonomy_term-eid-896-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 896,
          'revision_id' => 896,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982062,
          'changed' => 1459982062,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 1996,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 18,
    'uuid' => 'e5d7d546-e04f-4702-ace3-333f17176e28',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 1996,
    'entity_translation_handler_id' => 'taxonomy_term-eid-1170-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1170,
          'revision_id' => 1170,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982062,
          'changed' => 1459982062,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2003,
    'description' => NULL,
    'format' => NULL,
    'weight' => 13,
    'uuid' => 'ed8d1d88-0b9b-4d5e-b275-af2d39e39633',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2003,
    'entity_translation_handler_id' => 'taxonomy_term-eid-903-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 903,
          'revision_id' => 903,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982063,
          'changed' => 1459982063,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2012,
    'description' => NULL,
    'format' => NULL,
    'weight' => 4,
    'uuid' => 'f0d8b734-f64a-43cb-9875-bab1ffff9463',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2012,
    'entity_translation_handler_id' => 'taxonomy_term-eid-894-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 894,
          'revision_id' => 894,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982063,
          'changed' => 1459982063,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 2007,
    'description' => NULL,
    'format' => NULL,
    'weight' => 9,
    'uuid' => 'f8d80b86-8c41-4197-91e0-6d41e71313b1',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'name_original' => 2007,
    'entity_translation_handler_id' => 'taxonomy_term-eid-899-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 899,
          'revision_id' => 899,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982063,
          'changed' => 1459982063,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => NULL,
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 1991,
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 22,
    'uuid' => 'faec1eb2-1728-4831-91f6-437cf4399e30',
    'vocabulary_machine_name' => 'year',
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 1991,
    'entity_translation_handler_id' => 'taxonomy_term-eid-1166-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1166,
          'revision_id' => 1166,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459982063,
          'changed' => 1459982063,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  return $terms;
}
