<?php

/**
 * @file
 * Plugin definition.
 */

$plugin = array(
  'title' => t('FS Libby'),
  'icon' => 'flukestrap-libby.png',
  'category' => t('flukestrap'),
  'theme' => 'flukestrap_libby',
  'regions' => array(
    'title' => t('Title'),
    'header' => t('Header'),
    'slideshow' => t('Slideshow'),
    'alert-panel' => t('Alerts'),
    'key-features' => t('Key Features'),
    'libby-request-pricing' => t('Request Pricing'),
    'overview' => t('Overview'),
    'prod-models' => t('Models'),
    'prod-accessories' => t('Accessories'),
    'resources' => t('Resources'),
    'related' => t('Related Products'),
    ),
  );
