<?php
/**
 * @file
 * tax_solutions.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_solutions_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => "Energy Efficiency",
    'description' => NULL,
    'format' => 'panopoly_html_text',
    'weight' => 7,
    'uuid' => '1a6cf87c-f00e-4407-accc-e8c90b171411',
    'vocabulary_machine_name' => 'solutions',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_html_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Energy Efficiency',
    'entity_translation_handler_id' => 'taxonomy_term-eid-1272-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1272,
          'revision_id' => 1272,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1459882587,
          'changed' => 1459882587,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Fluke News",
    'description' => NULL,
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => '56f42274-e1d8-4a3f-8ce6-a65eb193a52a',
    'vocabulary_machine_name' => 'solutions',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_html_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Fluke News',
    'entity_translation_handler_id' => 'taxonomy_term-eid-1271-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1271,
          'revision_id' => 1271,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1459882559,
          'changed' => 1459882559,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Oil & Gas",
    'description' => NULL,
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '76e19568-9d8f-48f9-be90-f4397a41f041',
    'vocabulary_machine_name' => 'solutions',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_html_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Oil & Gas',
    'entity_translation_handler_id' => 'taxonomy_term-eid-1278-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1278,
          'revision_id' => 1278,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1459882738,
          'changed' => 1459882738,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'url_alias' => array(),
    'parent' => array(
      0 => 'de30a1b8-1838-481d-adfe-b4619ce382d7',
    ),
  );
  $terms[] = array(
    'name' => "Manufacturing",
    'description' => NULL,
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => '84f7d286-d135-4ab5-a8bb-d7dc6f529250',
    'vocabulary_machine_name' => 'solutions',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_html_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Manufacturing',
    'entity_translation_handler_id' => 'taxonomy_term-eid-1276-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1276,
          'revision_id' => 1276,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1459882662,
          'changed' => 1459882662,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'url_alias' => array(),
    'parent' => array(
      0 => 'de30a1b8-1838-481d-adfe-b4619ce382d7',
    ),
  );
  $terms[] = array(
    'name' => "Preventive Maintenance",
    'description' => NULL,
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => 'cbc19950-9eab-40a8-b7bd-8d34acb3ac7d',
    'vocabulary_machine_name' => 'solutions',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_html_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Preventive Maintenance',
    'entity_translation_handler_id' => 'taxonomy_term-eid-1274-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1274,
          'revision_id' => 1274,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1459882629,
          'changed' => 1459882629,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Chemical Processing",
    'description' => NULL,
    'format' => 'panopoly_html_text',
    'weight' => 1,
    'uuid' => 'cc5b83f4-e87c-484e-b1a3-0b62d837366c',
    'vocabulary_machine_name' => 'solutions',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_html_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Chemical Processing',
    'entity_translation_handler_id' => 'taxonomy_term-eid-1275-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1275,
          'revision_id' => 1275,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1459882651,
          'changed' => 1459882651,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'url_alias' => array(),
    'parent' => array(
      0 => 'de30a1b8-1838-481d-adfe-b4619ce382d7',
    ),
  );
  $terms[] = array(
    'name' => "Mining & Metals",
    'description' => NULL,
    'format' => 'panopoly_html_text',
    'weight' => 3,
    'uuid' => 'd4d1ae86-a508-473d-98bc-933260c89644',
    'vocabulary_machine_name' => 'solutions',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_html_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Mining & Metals',
    'entity_translation_handler_id' => 'taxonomy_term-eid-1277-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1277,
          'revision_id' => 1277,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1459882711,
          'changed' => 1459882711,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'url_alias' => array(),
    'parent' => array(
      0 => 'de30a1b8-1838-481d-adfe-b4619ce382d7',
    ),
  );
  $terms[] = array(
    'name' => "Industries",
    'description' => NULL,
    'format' => 'panopoly_html_text',
    'weight' => 2,
    'uuid' => 'de30a1b8-1838-481d-adfe-b4619ce382d7',
    'vocabulary_machine_name' => 'solutions',
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_html_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'field_url_title' => array(),
    'field_content_title' => array(),
    'name_original' => 'Industries',
    'entity_translation_handler_id' => 'taxonomy_term-eid-1273-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1273,
          'revision_id' => 1273,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1459882596,
          'changed' => 1459882596,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'url_alias' => array(),
  );
  return $terms;
}
