<?php
/**
 * @file
 * tax_meas_os.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_meas_os_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Power factor',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '207489f3-3427-4a7b-856a-26a7622da033',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1795,
          'revision_id' => 1795,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Reflections',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2570c7c4-5657-42b9-8c03-4a9c87f87f78',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1796,
          'revision_id' => 1796,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Rise-fall time',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '30095c9b-b56d-479d-aba4-14e71bf6bf13',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1797,
          'revision_id' => 1797,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Cursors',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '332437fd-8629-4f08-a106-b6574de834f4',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1790,
          'revision_id' => 1790,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Transients',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4217743a-bcc3-425e-9b0a-2330952e512a',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1798,
          'revision_id' => 1798,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Fast Fourier Transform (FFT)',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '54d88f24-7195-4dd3-b19f-bf68bd63364a',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1794,
          'revision_id' => 1794,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'VA',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '62ce1560-1eda-43df-bb91-821f38215c8a',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1799,
          'revision_id' => 1799,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Phase angle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6608a447-98a8-4d71-be08-9d5c8cbafb76',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1791,
          'revision_id' => 1791,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Jitter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6a08bce5-719f-4871-9181-0d70c0708543',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1792,
          'revision_id' => 1792,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Watts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7bd7dddb-634b-483a-9c68-d72601f1283f',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1801,
          'revision_id' => 1801,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Noise',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cff30e53-5c75-4f00-90b1-91a5ae779386',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1793,
          'revision_id' => 1793,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'VA reactive',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e3db1f5e-bdac-4e04-8132-13721ca1f970',
    'vocabulary_machine_name' => 'oscilloscopes',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1800,
          'revision_id' => 1800,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413230,
          'changed' => 1460413230,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  return $terms;
}
