<?php
/**
 * @file
 * tax_meas_volt.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_meas_volt_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => '600 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 5,
    'uuid' => '08c5652f-b3e6-41c7-90e6-22ad5f9af211',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1910,
          'revision_id' => 1910,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '31016468-f189-4d95-a637-5a5c31fed1b1',
    ),
  );
  $terms[] = array(
    'name' => '100 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0b1d0f0b-94cc-471f-96a1-e53faf27d96e',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1897,
          'revision_id' => 1897,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    ),
  );
  $terms[] = array(
    'name' => '300 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 2,
    'uuid' => '0bcb7f49-8183-479d-971f-279866aba0fd',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1901,
          'revision_id' => 1901,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '31016468-f189-4d95-a637-5a5c31fed1b1',
    ),
  );
  $terms[] = array(
    'name' => '1000 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 9,
    'uuid' => '0bfba508-30b8-4c58-80ff-85a98cbcf2e1',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1924,
          'revision_id' => 1924,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '31016468-f189-4d95-a637-5a5c31fed1b1',
    ),
  );
  $terms[] = array(
    'name' => '300 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 2,
    'uuid' => '0ef9f9f7-cdc7-43f3-82a9-0752bd8adce1',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1902,
          'revision_id' => 1902,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    ),
  );
  $terms[] = array(
    'name' => 'dc voltage sourcing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 33,
    'uuid' => '18713747-f45a-4f2d-b688-11e3fbf3701d',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1849,
          'revision_id' => 1849,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460414083,
          'changed' => 1460414083,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '800 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 7,
    'uuid' => '1cdc0498-494d-4ec7-8008-6a120a3079ab',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1916,
          'revision_id' => 1916,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '31016468-f189-4d95-a637-5a5c31fed1b1',
    ),
  );
  $terms[] = array(
    'name' => '500 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 4,
    'uuid' => '1e20954c-4d03-4151-a776-b43968a5eb69',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1907,
          'revision_id' => 1907,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '31016468-f189-4d95-a637-5a5c31fed1b1',
    ),
  );
  $terms[] = array(
    'name' => '600 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 5,
    'uuid' => '26868c13-6bf3-446e-9432-a985301f3919',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1911,
          'revision_id' => 1911,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    ),
  );
  $terms[] = array(
    'name' => '200 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 1,
    'uuid' => '27a04c94-7b7e-45a3-a77c-879fcc3b6aaf',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1898,
          'revision_id' => 1898,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '31016468-f189-4d95-a637-5a5c31fed1b1',
    ),
  );
  $terms[] = array(
    'name' => '600 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 5,
    'uuid' => '289e9900-7282-4b57-8a39-9721c73df09e',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1912,
          'revision_id' => 1912,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '474c444e-8935-4641-9ced-e944aa93f118',
    ),
  );
  $terms[] = array(
    'name' => 'Voltage channels',
    'description' => NULL,
    'format' => NULL,
    'weight' => 38,
    'uuid' => '2c32d7c9-d40f-456a-802b-06254e0fe934',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1841,
          'revision_id' => 1841,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413980,
          'changed' => 1460413980,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '500 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 4,
    'uuid' => '2eec31d6-f4f4-4dbd-9ca1-acf335532619',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1908,
          'revision_id' => 1908,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    ),
  );
  $terms[] = array(
    'name' => 'ac',
    'description' => NULL,
    'format' => NULL,
    'weight' => 30,
    'uuid' => '31016468-f189-4d95-a637-5a5c31fed1b1',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1847,
          'revision_id' => 1847,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460414018,
          'changed' => 1460414018,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '400 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 3,
    'uuid' => '343b8fb6-1eec-4144-aa81-5285abc4d4e6',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1905,
          'revision_id' => 1905,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    ),
  );
  $terms[] = array(
    'name' => '900 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 8,
    'uuid' => '3b755b94-1a33-47a5-938c-72cf8d186549',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1921,
          'revision_id' => 1921,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '474c444e-8935-4641-9ced-e944aa93f118',
    ),
  );
  $terms[] = array(
    'name' => 'LoZ: low input impedance',
    'description' => NULL,
    'format' => NULL,
    'weight' => 35,
    'uuid' => '3edaa773-7597-495f-b390-6bcd8a4f7abc',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1846,
          'revision_id' => 1846,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413980,
          'changed' => 1460413980,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'dc',
    'description' => NULL,
    'format' => NULL,
    'weight' => 32,
    'uuid' => '474c444e-8935-4641-9ced-e944aa93f118',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1848,
          'revision_id' => 1848,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460414018,
          'changed' => 1460414018,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Voltage detection',
    'description' => NULL,
    'format' => NULL,
    'weight' => 39,
    'uuid' => '50987a1a-9413-4d31-8bd2-d29d73bfbc23',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1839,
          'revision_id' => 1839,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413980,
          'changed' => 1460413980,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '900 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 8,
    'uuid' => '617b4ae1-ed0b-4190-be92-4912f93514da',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1919,
          'revision_id' => 1919,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '31016468-f189-4d95-a637-5a5c31fed1b1',
    ),
  );
  $terms[] = array(
    'name' => '400 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 3,
    'uuid' => '6bda51b1-f9a4-4e85-a0ec-8f6501b64b27',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1906,
          'revision_id' => 1906,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '474c444e-8935-4641-9ced-e944aa93f118',
    ),
  );
  $terms[] = array(
    'name' => '700 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 6,
    'uuid' => '7237acb5-943e-4825-9f5b-c9dd9855adbc',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1914,
          'revision_id' => 1914,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    ),
  );
  $terms[] = array(
    'name' => '800 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 7,
    'uuid' => '76637448-8d20-41e2-beb9-26a7d99abfda',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1917,
          'revision_id' => 1917,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    ),
  );
  $terms[] = array(
    'name' => 'Peak voltage',
    'description' => NULL,
    'format' => NULL,
    'weight' => 36,
    'uuid' => '76f84c91-f148-475a-8ce2-b7409cba4319',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1844,
          'revision_id' => 1844,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413980,
          'changed' => 1460413980,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '900 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 8,
    'uuid' => '79ece22d-9815-4634-8918-80dfc6d33125',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1920,
          'revision_id' => 1920,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    ),
  );
  $terms[] = array(
    'name' => '100 volts',
    'description' => '',
    'format' => 'panopoly_html_text',
    'weight' => 0,
    'uuid' => '834d8029-c7dc-4c78-bb9c-8c321ef7adfe',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1895,
          'revision_id' => 1895,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497980,
          'changed' => 1460497980,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '474c444e-8935-4641-9ced-e944aa93f118',
    ),
  );
  $terms[] = array(
    'name' => 'Low pass filter',
    'description' => NULL,
    'format' => NULL,
    'weight' => 34,
    'uuid' => '89ac35c7-a0a7-432c-aef2-8e52ba247eb4',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1845,
          'revision_id' => 1845,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413980,
          'changed' => 1460413980,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '800 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 7,
    'uuid' => '8ab2e48c-862a-42aa-8da3-4af61f12ec6c',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1918,
          'revision_id' => 1918,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '474c444e-8935-4641-9ced-e944aa93f118',
    ),
  );
  $terms[] = array(
    'name' => 'Voltage dips and swells',
    'description' => NULL,
    'format' => NULL,
    'weight' => 40,
    'uuid' => '8f8b529c-36d7-47a1-942e-53e08d900f82',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1842,
          'revision_id' => 1842,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413980,
          'changed' => 1460413980,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '1000 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 9,
    'uuid' => '96fc1109-abe9-4ed8-9580-39ac654ce99f',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1922,
          'revision_id' => 1922,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '474c444e-8935-4641-9ced-e944aa93f118',
    ),
  );
  $terms[] = array(
    'name' => '700 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 6,
    'uuid' => '9a17c08c-56d4-4932-a393-f2fe0391fc76',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1913,
          'revision_id' => 1913,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '31016468-f189-4d95-a637-5a5c31fed1b1',
    ),
  );
  $terms[] = array(
    'name' => '300 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 2,
    'uuid' => 'a5971973-9c5d-4c8b-8092-98ef9621114e',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1903,
          'revision_id' => 1903,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '474c444e-8935-4641-9ced-e944aa93f118',
    ),
  );
  $terms[] = array(
    'name' => 'THD measurement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 37,
    'uuid' => 'abea2b8e-e24c-466d-8e71-e33537265f1d',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1843,
          'revision_id' => 1843,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413980,
          'changed' => 1460413980,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '200 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 1,
    'uuid' => 'c2a06f38-a6fa-4075-a9b7-b4c9521434d5',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1899,
          'revision_id' => 1899,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    ),
  );
  $terms[] = array(
    'name' => '1000 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 9,
    'uuid' => 'c3872c5e-d234-4d80-9c2c-e952edf6e927',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1923,
          'revision_id' => 1923,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    ),
  );
  $terms[] = array(
    'name' => '700 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 6,
    'uuid' => 'cb16870e-7f26-4cab-a50e-c4cecd023012',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1915,
          'revision_id' => 1915,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '474c444e-8935-4641-9ced-e944aa93f118',
    ),
  );
  $terms[] = array(
    'name' => '400 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 3,
    'uuid' => 'cb91e916-e36b-492f-865f-dadfa59845a7',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1904,
          'revision_id' => 1904,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '31016468-f189-4d95-a637-5a5c31fed1b1',
    ),
  );
  $terms[] = array(
    'name' => '500 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 4,
    'uuid' => 'd267846a-34be-4dfe-915c-ab2a5648d58a',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1909,
          'revision_id' => 1909,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '474c444e-8935-4641-9ced-e944aa93f118',
    ),
  );
  $terms[] = array(
    'name' => '100 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd6fbcbe2-33fb-46a8-9fb9-5caf020bfcfd',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1896,
          'revision_id' => 1896,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '31016468-f189-4d95-a637-5a5c31fed1b1',
    ),
  );
  $terms[] = array(
    'name' => 'ac+dc',
    'description' => NULL,
    'format' => NULL,
    'weight' => 31,
    'uuid' => 'e8bc17d3-d1e8-4553-9f52-74d02f5d9624',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1838,
          'revision_id' => 1838,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460413980,
          'changed' => 1460413980,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => '200 volts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 1,
    'uuid' => 'f1ad5c64-fdba-4b99-ba6a-98510dbf244e',
    'vocabulary_machine_name' => 'voltage',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 1900,
          'revision_id' => 1900,
          'language' => 'en-us',
          'source' => '',
          'uid' => 4,
          'status' => 1,
          'translate' => 0,
          'created' => 1460497756,
          'changed' => 1460497756,
          'blocking' => 0,
        ),
      ),
    ),
    'url_alias' => array(),
    'parent' => array(
      0 => '474c444e-8935-4641-9ced-e944aa93f118',
    ),
  );
  return $terms;
}
