<?php
/**
 * @file
 * tax_software.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tax_software_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => "Accessories",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '0476dde1-bf74-4bb0-ac2c-02fea5dcabed',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Accessories',
    'entity_translation_handler_id' => 'taxonomy_term-eid-90-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 90,
          'revision_id' => 90,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981316,
          'changed' => 1459981316,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Portable Oscilloscopes",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '1247eabb-c1a7-4561-91b7-3da2883272d1',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Portable Oscilloscopes',
    'entity_translation_handler_id' => 'taxonomy_term-eid-82-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 82,
          'revision_id' => 82,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981316,
          'changed' => 1459981316,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Infrared Cameras",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '17b59e74-6420-4851-8278-00bc9c88bb83',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Infrared Cameras',
    'entity_translation_handler_id' => 'taxonomy_term-eid-84-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 84,
          'revision_id' => 84,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981318,
          'changed' => 1459981318,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Thermometers",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '41d3f551-54af-41a3-9529-c4c3bd21e4c1',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Thermometers',
    'entity_translation_handler_id' => 'taxonomy_term-eid-78-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 78,
          'revision_id' => 78,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981319,
          'changed' => 1459981319,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Digital Multimeters",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '5594eec1-3c34-4143-9a30-5d39d8c5bb03',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Digital Multimeters',
    'entity_translation_handler_id' => 'taxonomy_term-eid-87-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 87,
          'revision_id' => 87,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981321,
          'changed' => 1459981321,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Power Quality Analyzers",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '5a994423-2cda-4e0b-89ad-0146f38174a3',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Power Quality Analyzers',
    'entity_translation_handler_id' => 'taxonomy_term-eid-80-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 80,
          'revision_id' => 80,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981321,
          'changed' => 1459981321,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Clamp Meters",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '5b184aec-958f-4914-ba29-9f1632304939',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Clamp Meters',
    'entity_translation_handler_id' => 'taxonomy_term-eid-88-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 88,
          'revision_id' => 88,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981321,
          'changed' => 1459981321,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Wireless Testers",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '6048b670-e373-445e-bc7a-6e129997e807',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Wireless Testers',
    'entity_translation_handler_id' => 'taxonomy_term-eid-75-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 75,
          'revision_id' => 75,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981321,
          'changed' => 1459981321,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Visual IR Thermometers",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '6d9d76dd-e041-4fbe-a4c1-fb28e88d6fde',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Visual IR Thermometers',
    'entity_translation_handler_id' => 'taxonomy_term-eid-76-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 76,
          'revision_id' => 76,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981322,
          'changed' => 1459981322,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "HVAC IAQ",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '7295d531-3dcb-4844-a607-8fc14f664de2',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'HVAC IAQ',
    'entity_translation_handler_id' => 'taxonomy_term-eid-85-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 85,
          'revision_id' => 85,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981322,
          'changed' => 1459981322,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Pressure Calibrators",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '775da5a9-881c-4fc8-94d9-81e2fde283fc',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Pressure Calibrators',
    'entity_translation_handler_id' => 'taxonomy_term-eid-79-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 79,
          'revision_id' => 79,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981322,
          'changed' => 1459981322,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Electrical Testers",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => '7ee102bc-bd69-499a-9623-b9ab0f479da9',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Electrical Testers',
    'entity_translation_handler_id' => 'taxonomy_term-eid-86-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 86,
          'revision_id' => 86,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981322,
          'changed' => 1459981322,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Vibration",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => 'af420095-b1b0-428c-b9ad-9013185bcb22',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Vibration',
    'entity_translation_handler_id' => 'taxonomy_term-eid-77-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 77,
          'revision_id' => 77,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981325,
          'changed' => 1459981325,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Battery Analyzers",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => 'd3dc5886-6e42-467b-be8e-810474a46291',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Battery Analyzers',
    'entity_translation_handler_id' => 'taxonomy_term-eid-89-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 89,
          'revision_id' => 89,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981328,
          'changed' => 1459981328,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Power and Energy Loggers",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => 'd629aad1-e28d-447d-a917-f47f00577dec',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Power and Energy Loggers',
    'entity_translation_handler_id' => 'taxonomy_term-eid-81-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 81,
          'revision_id' => 81,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981328,
          'changed' => 1459981328,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => "Multifunction Calibrators",
    'description' => NULL,
    'format' => 'panopoly_wysiwyg_text',
    'weight' => 0,
    'uuid' => 'd8fbea9a-8f00-4239-9095-f88ff7bbdb26',
    'vocabulary_machine_name' => 'software',
    'field_header_banner_image' => array(),
    'field_content_title' => array(),
    'field_url_title' => array(),
    'name_field' => array(),
    'description_field' => array(
      'en-us' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'panopoly_wysiwyg_text',
          'safe_value' => '',
          'safe_summary' => '',
        ),
      ),
    ),
    'name_original' => 'Multifunction Calibrators',
    'entity_translation_handler_id' => 'taxonomy_term-eid-83-0',
    'translations' => array(
      'original' => 'en-us',
      'data' => array(
        'en-us' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => 83,
          'revision_id' => 83,
          'language' => 'en-us',
          'source' => '',
          'uid' => 1,
          'status' => 1,
          'translate' => 0,
          'created' => 1459981328,
          'changed' => 1459981328,
          'blocking' => 0,
        ),
      ),
    ),
    'description_original' => '',
    'path' => array(
      'pathauto' => 1,
    ),
    'url_alias' => array(),
  );
  return $terms;
}
