<?php
/**
 * @file
 * fluke_languages.features.language.inc
 */

/**
 * Implements hook_locale_default_languages().
 */
function fluke_languages_locale_default_languages() {
  $languages = array();

  // Exported language: cs-cz.
  $languages['cs-cz'] = array(
    'language' => 'cs-cz',
    'name' => 'cs-cz',
    'native' => 'Czech / Czech Republic',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'cs-cz',
    'weight' => -8,
    'parent' => 'en-us',
  );
  // Exported language: da-dk.
  $languages['da-dk'] = array(
    'language' => 'da-dk',
    'name' => 'da-dk',
    'native' => 'Danish / Denmark',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'da-dk',
    'weight' => -7,
    'parent' => 'en-us',
  );
  // Exported language: de-at.
  $languages['de-at'] = array(
    'language' => 'de-at',
    'name' => 'de-at',
    'native' => 'German / Austria',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'de-at',
    'weight' => -5,
    'parent' => 'de-de',
  );
  // Exported language: de-ch.
  $languages['de-ch'] = array(
    'language' => 'de-ch',
    'name' => 'de-ch',
    'native' => 'German / Switzerland',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'de-ch',
    'weight' => -4,
    'parent' => 'de-de',
  );
  // Exported language: de-de.
  $languages['de-de'] = array(
    'language' => 'de-de',
    'name' => 'de-de',
    'native' => 'German / Germany',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'de-de',
    'weight' => -6,
    'parent' => 'en-us',
  );
  // Exported language: en.
  $languages['en'] = array(
    'language' => 'en',
    'name' => 'DELETE ME - English',
    'native' => 'DELETE ME - English',
    'direction' => 0,
    'enabled' => 0,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en',
    'weight' => -10,
    'parent' => '',
  );
  // Exported language: en-au.
  $languages['en-au'] = array(
    'language' => 'en-au',
    'name' => 'en-au',
    'native' => 'English / Australia',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-au',
    'weight' => -3,
    'parent' => 'en-us',
  );
  // Exported language: en-ca.
  $languages['en-ca'] = array(
    'language' => 'en-ca',
    'name' => 'en-ca',
    'native' => 'English / Canada',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-ca',
    'weight' => -2,
    'parent' => 'en-us',
  );
  // Exported language: en-gb.
  $languages['en-gb'] = array(
    'language' => 'en-gb',
    'name' => 'en-gb',
    'native' => 'English / United Kingdom',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-gb',
    'weight' => -1,
    'parent' => 'en-us',
  );
  // Exported language: en-id.
  $languages['en-id'] = array(
    'language' => 'en-id',
    'name' => 'en-id',
    'native' => 'English / Indonesia',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-id',
    'weight' => 1,
    'parent' => 'en-us',
  );
  // Exported language: en-ie.
  $languages['en-ie'] = array(
    'language' => 'en-ie',
    'name' => 'en-ie',
    'native' => 'English / Ireland',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-ie',
    'weight' => 0,
    'parent' => 'en-gb',
  );
  // Exported language: en-in.
  $languages['en-in'] = array(
    'language' => 'en-in',
    'name' => 'en-in',
    'native' => 'English / India',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-in',
    'weight' => 2,
    'parent' => 'en-us',
  );
  // Exported language: en-my.
  $languages['en-my'] = array(
    'language' => 'en-my',
    'name' => 'en-my',
    'native' => 'English / Malaysia',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-my',
    'weight' => 3,
    'parent' => 'en-us',
  );
  // Exported language: en-ph.
  $languages['en-ph'] = array(
    'language' => 'en-ph',
    'name' => 'en-ph',
    'native' => 'English / Philippines',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-ph',
    'weight' => 4,
    'parent' => 'en-us',
  );
  // Exported language: en-sg.
  $languages['en-sg'] = array(
    'language' => 'en-sg',
    'name' => 'en-sg',
    'native' => 'English / Singapore',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-sg',
    'weight' => 5,
    'parent' => 'en-us',
  );
  // Exported language: en-th.
  $languages['en-th'] = array(
    'language' => 'en-th',
    'name' => 'en-th',
    'native' => 'English / Thailand',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-th',
    'weight' => 6,
    'parent' => 'en-us',
  );
  // Exported language: en-tt.
  $languages['en-tt'] = array(
    'language' => 'en-tt',
    'name' => 'en-tt',
    'native' => 'English / Trinidad/Tobago',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-tt',
    'weight' => 7,
    'parent' => 'en-us',
  );
  // Exported language: en-us.
  $languages['en-us'] = array(
    'language' => 'en-us',
    'name' => 'en-us',
    'native' => 'English / United States',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-us',
    'weight' => -9,
    'parent' => '',
  );
  // Exported language: en-vn.
  $languages['en-vn'] = array(
    'language' => 'en-vn',
    'name' => 'en-vn',
    'native' => 'English / Vietnam',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'en-vn',
    'weight' => 8,
    'parent' => 'en-us',
  );
  // Exported language: es-ar.
  $languages['es-ar'] = array(
    'language' => 'es-ar',
    'name' => 'es-ar',
    'native' => 'Spanish LAES / Argentina',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-ar',
    'weight' => 11,
    'parent' => 'es-mx',
  );
  // Exported language: es-bo.
  $languages['es-bo'] = array(
    'language' => 'es-bo',
    'name' => 'es-bo',
    'native' => 'Spanish LAES / Bolivia',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-bo',
    'weight' => 12,
    'parent' => 'es-mx',
  );
  // Exported language: es-cl.
  $languages['es-cl'] = array(
    'language' => 'es-cl',
    'name' => 'es-cl',
    'native' => 'Spanish LAES / Chile',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-cl',
    'weight' => 13,
    'parent' => 'es-mx',
  );
  // Exported language: es-co.
  $languages['es-co'] = array(
    'language' => 'es-co',
    'name' => 'es-co',
    'native' => 'Spanish LAES / Colombia',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-co',
    'weight' => 14,
    'parent' => 'es-mx',
  );
  // Exported language: es-cr.
  $languages['es-cr'] = array(
    'language' => 'es-cr',
    'name' => 'es-cr',
    'native' => 'Spanish LAES / Costa Rica',
    'direction' => 0,
    'enabled' => 0,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-cr',
    'weight' => 15,
    'parent' => 'es-mx',
  );
  // Exported language: es-do.
  $languages['es-do'] = array(
    'language' => 'es-do',
    'name' => 'es-do',
    'native' => 'Spanish LAES / Dominican Republic',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-do',
    'weight' => 16,
    'parent' => 'es-mx',
  );
  // Exported language: es-ec.
  $languages['es-ec'] = array(
    'language' => 'es-ec',
    'name' => 'es-ec',
    'native' => 'Spanish LAES / Ecuador',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-ec',
    'weight' => 17,
    'parent' => 'es-mx',
  );
  // Exported language: es-es.
  $languages['es-es'] = array(
    'language' => 'es-es',
    'name' => 'es-es',
    'native' => 'Spanish / Spain',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-es',
    'weight' => 9,
    'parent' => 'en-us',
  );
  // Exported language: es-gt.
  $languages['es-gt'] = array(
    'language' => 'es-gt',
    'name' => 'es-gt',
    'native' => 'Spanish LAES / Guatemala',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-gt',
    'weight' => 18,
    'parent' => 'es-mx',
  );
  // Exported language: es-mx.
  $languages['es-mx'] = array(
    'language' => 'es-mx',
    'name' => 'es-mx',
    'native' => 'Spanish LAES / Mexico',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-mx',
    'weight' => 10,
    'parent' => 'en-us',
  );
  // Exported language: es-pe.
  $languages['es-pe'] = array(
    'language' => 'es-pe',
    'name' => 'es-pe',
    'native' => 'Spanish LAES / Peru',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-pe',
    'weight' => 19,
    'parent' => 'es-mx',
  );
  // Exported language: es-sv.
  $languages['es-sv'] = array(
    'language' => 'es-sv',
    'name' => 'es-sv',
    'native' => 'Spanish LAES / El Salvador',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-sv',
    'weight' => 20,
    'parent' => 'es-mx',
  );
  // Exported language: es-uy.
  $languages['es-uy'] = array(
    'language' => 'es-uy',
    'name' => 'es-uy',
    'native' => 'Spanish LAES / Uruguay',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-uy',
    'weight' => 21,
    'parent' => 'es-mx',
  );
  // Exported language: es-ve.
  $languages['es-ve'] = array(
    'language' => 'es-ve',
    'name' => 'es-ve',
    'native' => 'Spanish LAES / Venezuela',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es-ve',
    'weight' => 22,
    'parent' => 'es-mx',
  );
  // Exported language: fi-fi.
  $languages['fi-fi'] = array(
    'language' => 'fi-fi',
    'name' => 'fi-fi',
    'native' => 'Finish / Finland',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fi-fi',
    'weight' => 28,
    'parent' => 'en-us',
  );
  // Exported language: fr-be.
  $languages['fr-be'] = array(
    'language' => 'fr-be',
    'name' => 'fr-be',
    'native' => 'French / Belgium',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fr-be',
    'weight' => 30,
    'parent' => 'fr-fr',
  );
  // Exported language: fr-ca.
  $languages['fr-ca'] = array(
    'language' => 'fr-ca',
    'name' => 'fr-ca',
    'native' => 'French / Canada',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fr-ca',
    'weight' => 31,
    'parent' => 'fr-fr',
  );
  // Exported language: fr-ch.
  $languages['fr-ch'] = array(
    'language' => 'fr-ch',
    'name' => 'fr-ch',
    'native' => 'French / Switzerland',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fr-ch',
    'weight' => 32,
    'parent' => 'fr-fr',
  );
  // Exported language: fr-fr.
  $languages['fr-fr'] = array(
    'language' => 'fr-fr',
    'name' => 'fr-fr',
    'native' => 'French / France',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fr-fr',
    'weight' => 29,
    'parent' => 'en-us',
  );
  // Exported language: id-id.
  $languages['id-id'] = array(
    'language' => 'id-id',
    'name' => 'id-id',
    'native' => 'Bahasa / Indonesia',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'id-id',
    'weight' => 33,
    'parent' => 'en-us',
  );
  // Exported language: it-ch.
  $languages['it-ch'] = array(
    'language' => 'it-ch',
    'name' => 'it-ch',
    'native' => 'Italian / Switzerland',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'it-ch',
    'weight' => 35,
    'parent' => 'it-it',
  );
  // Exported language: it-it.
  $languages['it-it'] = array(
    'language' => 'it-it',
    'name' => 'it-it',
    'native' => 'Italian / Italy',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'it-it',
    'weight' => 34,
    'parent' => 'en-us',
  );
  // Exported language: ja-jp.
  $languages['ja-jp'] = array(
    'language' => 'ja-jp',
    'name' => 'ja-jp',
    'native' => 'Japanese / Japan ',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ja-jp',
    'weight' => 36,
    'parent' => 'en-us',
  );
  // Exported language: ko-kr.
  $languages['ko-kr'] = array(
    'language' => 'ko-kr',
    'name' => 'ko-kr',
    'native' => 'Korean / Korea',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ko-kr',
    'weight' => 37,
    'parent' => 'en-us',
  );
  // Exported language: nl-be.
  $languages['nl-be'] = array(
    'language' => 'nl-be',
    'name' => 'nl-be',
    'native' => 'Dutch / Belgium',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'nl-be',
    'weight' => 39,
    'parent' => 'nl-nl',
  );
  // Exported language: nl-nl.
  $languages['nl-nl'] = array(
    'language' => 'nl-nl',
    'name' => 'nl-nl',
    'native' => 'Dutch / Netherlands',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'nl-nl',
    'weight' => 38,
    'parent' => 'en-us',
  );
  // Exported language: no-no.
  $languages['no-no'] = array(
    'language' => 'no-no',
    'name' => 'no-no',
    'native' => 'Norwegian / Norway',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'no-no',
    'weight' => 40,
    'parent' => 'en-us',
  );
  // Exported language: pl-pl.
  $languages['pl-pl'] = array(
    'language' => 'pl-pl',
    'name' => 'pl-pl',
    'native' => 'Polish / Poland',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'pl-pl',
    'weight' => 41,
    'parent' => 'en-us',
  );
  // Exported language: pt-br.
  $languages['pt-br'] = array(
    'language' => 'pt-br',
    'name' => 'pt-br',
    'native' => 'Portuguese Brazil / Brazil',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'pt-br',
    'weight' => 42,
    'parent' => 'en-us',
  );
  // Exported language: pt-pt.
  $languages['pt-pt'] = array(
    'language' => 'pt-pt',
    'name' => 'pt-pt',
    'native' => 'Portuguese / Portugal',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'pt-pt',
    'weight' => 43,
    'parent' => 'en-us',
  );
  // Exported language: ro-ro.
  $languages['ro-ro'] = array(
    'language' => 'ro-ro',
    'name' => 'ro-ro',
    'native' => 'Romanian / Romania',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ro-ro',
    'weight' => 44,
    'parent' => 'en-us',
  );
  // Exported language: ru-ru.
  $languages['ru-ru'] = array(
    'language' => 'ru-ru',
    'name' => 'ru-ru',
    'native' => 'Russian / Russia',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ru-ru',
    'weight' => 45,
    'parent' => 'en-us',
  );
  // Exported language: sv-se.
  $languages['sv-se'] = array(
    'language' => 'sv-se',
    'name' => 'sv-se',
    'native' => 'Swedish / Sweden',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sv-se',
    'weight' => 46,
    'parent' => 'en-us',
  );
  // Exported language: th-th.
  $languages['th-th'] = array(
    'language' => 'th-th',
    'name' => 'th-th',
    'native' => 'Thai / Thailand',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'th-th',
    'weight' => 23,
    'parent' => 'en-us',
  );
  // Exported language: tr-tr.
  $languages['tr-tr'] = array(
    'language' => 'tr-tr',
    'name' => 'tr-tr',
    'native' => 'Turkish / Turkey',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'tr-tr',
    'weight' => 24,
    'parent' => 'en-us',
  );
  // Exported language: vi-vn.
  $languages['vi-vn'] = array(
    'language' => 'vi-vn',
    'name' => 'vi-vn',
    'native' => 'Vietnamese / Vietnam',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'vi-vn',
    'weight' => 25,
    'parent' => 'en-us',
  );
  // Exported language: zh-cn.
  $languages['zh-cn'] = array(
    'language' => 'zh-cn',
    'name' => 'zh-cn',
    'native' => 'Chinese Simplified / China',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'zh-cn',
    'weight' => 26,
    'parent' => 'en-us',
  );
  // Exported language: zh-tw.
  $languages['zh-tw'] = array(
    'language' => 'zh-tw',
    'name' => 'zh-tw',
    'native' => 'Chinese Traditional / Taiwan',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'zh-tw',
    'weight' => 27,
    'parent' => 'en-us',
  );
  return $languages;
}
