<?php
/**
 * @file
 * Responsive panels layouts for Panopoly.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function flukestrap_layouts_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_ctools_plugin_post_alter().
 *
 * @param $plugin
 * @param $info
 */
function flukestrap_layouts_ctools_plugin_post_alter(&$plugin, &$info) {
  // Switch Panopoly Layouts to flukestrap Layouts.
  if ($info['type'] == 'layouts' && $plugin['module'] == 'panopoly_theme') {
    if (strpos($plugin['theme'], 'flukestrap_') === FALSE) {
      $new_name = 'flukestrap_' . $plugin['theme'];
      $path = drupal_get_path('module', 'flukestrap_layouts') . '/plugins/layouts/' . $new_name;
      if (file_exists($path)) {
        $plugin['theme'] = $new_name;
        $plugin['file'] = 'flukestrap_' . $plugin['file'];
        $plugin['path'] = $path;
        $plugin['icon'] = 'flukestrap-' . $plugin['icon'];
        unset($plugin['css']);
      }
    }
  }
}